/* =====================================================================
   BALIKÇI TYCOON — ÖZEL İSİMLİ MÜŞTERİLER  (bu dosyayı serbestçe düzenle)
   ---------------------------------------------------------------------
   Her gün havuzdan 2 kişi gelir (dün gelenler ertesi gün tekrar gelmez).
   Yeni kişi eklemek = listeye yeni bir { ... } bloğu eklemek. Silmek = bloğu silmek.
   Tüm karakterler özgündür; gerçek kişilerle herhangi bir benzerlik tesadüftür.
   KURAL (mağaza yayını): gerçek, yaşayan ya da yakın zamanda ölmüş ünlülerin adını, lakabını, imza sözünü,
   şarkı sözünü veya tanınır görünüşünü kullanma. Halk fıkrası kahramanları (Temel, Nasreddin Hoca) serbesttir.

   ZORUNLU ALANLAR
     id    : benzersiz kısa kimlik (küçük harf, boşluksuz)   örn. 'temel'
     n     : ekranda görünen isim — tek dil 'Temel' ya da iki dil { tr: 'Tek Göz Recep', en: 'One-Eyed Renny' }
     job   : meslek          { tr: '...', en: '...' }  (ya da tek dilde 'metin')
     hi    : kuyruğa girince söylediği   { tr, en }
     bye   : mutlu ayrılırken söylediği  { tr, en }

   İSTEĞE BAĞLI — KARAKTER
     trait : huyu / özelliği (menü › ALBÜM'de görünür)   { tr, en }
     fav   : sevdiği balık: hamsi | uskumru | palamut | levrek | somon | ton
             (o tezgâh açıksa oraya gider, değilse açık herhangi bir tezgâha)

   İSTEĞE BAĞLI — OYUN ETKİSİ (yazılmazsa varsayılan)
     qty   : sipariş adedi [en az, en çok]          varsayılan [3, 5]
     pat   : sabır (saniye)                          varsayılan 150
     tip   : ödeme çarpanı (1 = normal fiyat)        varsayılan 1.1
     rep   : verdiği itibar                          varsayılan 3
     fx    : başının üstünden uçuşan işaret: '♪' '♥' '✦' '!' '?' '$' '~' '·'
     sfx   : gelince ve mutlu giderken çalan hafif ses:
             hmm chime whistle bell kiss guitar sing eyo laugh sigh kick robot
             gull parrot meow camera cash drum sizzle fanfare
     fxc   : işaretin rengi                          örn. '#ff6b8a'
     moon  : true → geri geri kayarak yürür (moonwalk)
     dance : true → kuyrukta hoplayıp dans eder

   GÖRÜNÜŞ — look: { ... }   (renkler '#rrggbb')
     sk        : ten 0 açık … 3 koyu
     hair      : saç rengi          hairStyle: 0 kısa, 1 dalgalı, 2 uzun, 3 at kuyruğu,
                                               4 kel, 5 kıvırcık/afro, 6 topuz, 7 mohikan, 8 kabarık perçem
     coat/coat2: üst giysi + omuz ışığı     pants: pantolon     skirt: uzun etek (pantolon yerine)
     tall / short / belly : 1 → uzun boy / kısa boy / göbekli
     Başlık (biri): cap, beanie, sunHat, tophat, turban (renk)  ·  fez, chefHat (true)  ·  scarf (başörtüsü, renk) + scarfDots
     Yüz: must, thickMust, beard (true) · glasses, shades (güneş gözlüğü), eyepatch, pipe (true)
     Üst: apron, vest, sash, tie, bowtie, cape (pelerin), scales (balık pulu desenli elbise), knit, headband (renk)
          chain (altın kolye, true)
     Eşya: bag, notebook, mic, phone (true) · bigBag, guitar, bird (omuzda kuş) (renk)
   ===================================================================== */
window.BT_SPECIALS = [

  /* ---------- İLK 10: mahallenin tanıdık yüzleri ---------- */
  { id: 'caner', n: { tr: 'Caner', en: 'Caner' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Kaliteci', en: 'Quality inspector' },
    trait: { tr: 'Her balığı tek tek inceler; kedilere mutlaka pay ayırır.', en: 'Inspects every fish; always saves a share for the cats.' },
    look: { tall: 1, belly: 1, coat: '#5b6d7c', coat2: '#6f8394', hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#33393f' },
    hi: { tr: 'Önce bir bakayım… tamam, bundan alalım.', en: 'Let me take a look… right, I\'ll have this.' },
    bye: { tr: 'Kalitesi yerinde. Kedilere de bir parça ayırdım.', en: 'Quality checks out. Saved a bite for the cats.' } },
  { id: 'pelin', n: { tr: 'Pelin', en: 'Pelin' }, sfx: 'chime', fav: 'levrek', job: { tr: 'Biyolog', en: 'Biologist' },
    trait: { tr: 'Solungaca bakıp tazeliği saniyede söyler.', en: 'Reads freshness from the gills in a second.' },
    look: { coat: '#3f7f7a', coat2: '#56988f', hair: '#d9772b', hairStyle: 5, sk: 0, pants: '#2b3a45' },
    hi: { tr: 'Gözleri parlak, solungaçlar kırmızı. Güzel.', en: 'Bright eyes, red gills. Good.' },
    bye: { tr: 'Net ve temiz. Teşekkürler.', en: 'Clean and precise. Thank you.' } },
  { id: 'riza', n: { tr: 'Rıza', en: 'Rıza' }, sfx: 'whistle', fav: 'hamsi', job: { tr: 'Tesisat ustası', en: 'Plumber' },
    trait: { tr: 'Sabahın köründe gelir, işe balıkla başlar.', en: 'Shows up at dawn; the day starts with fish.' },
    look: { belly: 1, coat: '#3f5f8f', coat2: '#557aa8', cap: '#2b2b2b', thickMust: true, hair: '#1d1713', hairStyle: 0, sk: 2, pants: '#2e3a4a' },
    hi: { tr: 'Sabahın köründe iş başı, önce balık!', en: 'Up at dawn — fish comes first!' },
    bye: { tr: 'Eline sağlık. Musluk bozulursa bana haber ver.', en: 'Cheers. If a tap leaks, you know who to call.' } },
  { id: 'nermin', n: { tr: 'Nermin', en: 'Nermin' }, sfx: 'bell', fav: 'uskumru', job: { tr: 'Emekli öğretmen', en: 'Retired teacher' },
    trait: { tr: 'Tezgâha not verir; düzenliysen bahşişi artar.', en: 'Grades your stall; tidy stalls get a better tip.' },
    tip: 1.25,
    look: { short: 1, belly: 1, coat: '#8a4a6a', coat2: '#a45f82', hair: '#9a9a96', hairStyle: 1, sk: 0, skirt: '#4a3a4a', bigBag: '#6b2f3a' },
    hi: { tr: 'Evladım, bugün hangisi taze?', en: 'Dear, which one is fresh today?' },
    bye: { tr: 'Aferin sana. Hep böyle düzenli ol.', en: 'Well done, dear. Keep it this tidy.' } },
  { id: 'kemal', n: { tr: 'Kemal', en: 'Kemal' }, sfx: 'cash', fav: 'levrek', job: { tr: 'Lokanta işletmecisi', en: 'Restaurant owner' },
    trait: { tr: 'Akşam servisi için toplu alır.', en: 'Buys in bulk for the evening service.' },
    qty: [5, 8],
    look: { tall: 1, coat: '#e8e2d2', coat2: '#f4efe4', vest: '#3a2f28', notebook: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2a2724' },
    hi: { tr: 'Akşam servisi için not alıyorum…', en: 'Taking notes for tonight\'s service…' },
    bye: { tr: 'Yarın yine gelirim, masalar dolu.', en: 'Back tomorrow — the tables are full.' } },
  { id: 'sule', n: { tr: 'Şule', en: 'Şule' }, sfx: 'chime', fav: 'uskumru', job: { tr: 'Terzi', en: 'Tailor' },
    trait: { tr: 'Paketin dikişine bile bakar.', en: 'Even checks the seams on the wrapping.' },
    look: { coat: '#7a2b4a', coat2: '#94405f', hair: '#3d2a1a', hairStyle: 6, sk: 0, skirt: '#2f3a5a' },
    hi: { tr: 'Tezgâhın ne kadar derli toplu, beğendim.', en: 'Such a neat stall. I like it.' },
    bye: { tr: 'Paketi de özenli yapmışsın, sağ ol.', en: 'Wrapped with care, too. Thank you.' } },
  { id: 'okan', n: { tr: 'Okan', en: 'Okan' }, sfx: 'bell', fav: 'hamsi', job: { tr: 'Kurye', en: 'Courier' },
    trait: { tr: 'Hep acelesi var; çabuk servis ister.', en: 'Always in a hurry; wants it fast.' },
    pat: 95,
    look: { coat: '#e0a030', coat2: '#f0bd55', bag: true, hair: '#1d1713', hairStyle: 0, sk: 2, pants: '#2b3a45' },
    hi: { tr: 'Çabuk olursak iyi olur, teslimat bekliyor!', en: 'Quick if we can — a delivery\'s waiting!' },
    bye: { tr: 'Hızlı servis, tam benlik!', en: 'Fast service, just my style!' } },
  { id: 'fatos', n: { tr: 'Fatoş', en: 'Fatoş' }, sfx: 'sizzle', fav: 'uskumru', job: { tr: 'Ev aşçısı', en: 'Home cook' },
    trait: { tr: 'Buğulama ustası; herkese bir tabak ayırır.', en: 'Steamed-fish expert; saves everyone a plate.' },
    look: { belly: 1, coat: '#c8553d', coat2: '#dc6d55', scarf: '#e0679e', scarfDots: '#ffd76a', apron: '#f0ece0', hair: '#3d2a1a', sk: 1, skirt: '#5a3f7a' },
    hi: { tr: 'Bu akşam buğulama yapacağım, en tazesinden!', en: 'Steamed fish tonight — the freshest, please!' },
    bye: { tr: 'Afiyetle yiyelim, sana da bir tabak ayırırım!', en: 'Enjoy! I\'ll save you a plate!' } },
  { id: 'burak', n: { tr: 'Burak', en: 'Burak' }, sfx: 'cash', fav: 'levrek', job: { tr: 'Bankacı', en: 'Banker' },
    trait: { tr: 'Kuruşu kuruşuna öder, fazlasını değil.', en: 'Pays to the penny, not a penny more.' },
    tip: 1.0,
    look: { coat: '#2f3f5a', coat2: '#43557a', vest: '#e8e2d2', beard: true, tie: '#8d2a2a', hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#252c38' },
    hi: { tr: 'Hesap kitap tamam, şimdi balık zamanı.', en: 'Books are balanced — fish time.' },
    bye: { tr: 'Teşekkürler, iyi işler.', en: 'Thanks. Good business to you.' } },
  { id: 'ayfer', n: { tr: 'Ayfer', en: 'Ayfer' }, sfx: 'chime', fav: 'hamsi', job: { tr: 'Eczacı', en: 'Pharmacist' },
    trait: { tr: 'Balığı reçete gibi yazar: haftada iki kez.', en: 'Prescribes fish: twice a week.' },
    look: { coat: '#f0ece0', coat2: '#fbf8f0', glasses: true, hair: '#3d2a1a', hairStyle: 1, sk: 0, pants: '#3a4450' },
    hi: { tr: 'Omega-3 için haftada iki kez balık, reçetem bu.', en: 'Fish twice a week — that\'s my prescription.' },
    bye: { tr: 'Düzenli beslenmek önemli. Görüşürüz.', en: 'Eat regularly. See you soon.' } },

  /* ---------- MEŞHUR TİPLER — sahnenin, ekranın, mutfağın renkli yüzleri (hepsi özgün karakterdir) ---------- */
  { id: 'tarkut', n: { tr: 'Kıvanç Parıltı', en: 'Kivanch Sparkle' }, sfx: 'kiss', fav: 'levrek', job: { tr: 'Pop Megastarı', en: 'Pop megastar' },
    trait: { tr: 'Öpücük atmadan balık almaz; kuyrukta pul pul ceketiyle dans eder.', en: 'Won\'t buy without blowing a kiss; dances in the queue in his sequin jacket.' },
    fx: '♥', fxc: '#ff6b8a', dance: true, tip: 1.4,
    look: { coat: '#5a1f6b', coat2: '#7a3590', chain: true, hair: '#3a1f12', hairStyle: 7, sk: 1, pants: '#1a1a20' },
    hi: { tr: 'Parlayan pullar, parlayan levrek… bir tane lütfen!', en: 'Shiny scales, shiny sea bass… one, please!' },
    bye: { tr: 'Sahnede görüşürüz, tezgâh! Öpücükler!', en: 'See you on stage, stall! Kisses!' } },
  { id: 'cemal', n: { tr: 'Kahkaha Kadir', en: 'Chuckle Kadir' }, sfx: 'laugh', fav: 'palamut', job: { tr: 'Stand-up komedyeni', en: 'Stand-up comedian' },
    trait: { tr: 'Kuyrukta şov yapar; herkes güldüğü için kimse sabırsızlanmaz.', en: 'Does a set in the queue; everyone laughs, so nobody gets impatient.' },
    fx: '!', fxc: '#ffd76a', pat: 230,
    look: { coat: '#6a3a22', coat2: '#85502e', glasses: true, hair: '#1d1713', hairStyle: 5, sk: 1, pants: '#1f252c' },
    hi: { tr: 'Balıkçıya girdim, balık bana dedi ki: "Abi, sen de mi tuzlusun?"', en: 'I walk into the fish shop and the fish says: "You salty too, pal?"' },
    bye: { tr: 'Harika seyircisiniz! Bahşişler kovaya!', en: 'Great crowd! Tips in the bucket!' } },
  { id: 'sukru', n: { tr: 'Saf Sadık', en: 'Simple Sadik' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Mahalle bekçisi', en: 'Night watchman' },
    trait: { tr: 'Saf ama altın kalpli; siparişini iki kez sorar, bahşişi bol.', en: 'Naive with a heart of gold; asks twice, tips big.' },
    tip: 1.5,
    look: { short: 1, coat: '#6b5a3a', coat2: '#85714c', vest: '#3a2f22', cap: '#c9a15e', must: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#3a3226' },
    hi: { tr: 'Ben bi\' şey demedim… balık dedi ki beni al!', en: 'I didn\'t say a thing… the fish said "take me"!' },
    bye: { tr: 'Hıh! Çok şükür, doyduk.', en: 'Heh! Thank goodness, we\'re fed.' } },
  { id: 'barlas', n: { tr: 'Yüzüklü Yavuz', en: 'Ringed Yavuz' }, sfx: 'guitar', fav: 'uskumru', job: { tr: 'Rock ozanı', en: 'Rock bard' },
    trait: { tr: 'Parmakları yüzük dolu; her alışverişte tezgâha bir nasihat bırakır.', en: 'Fingers full of rings; leaves the stall a piece of advice with every purchase.' },
    fx: '♪', fxc: '#c9a0ff',
    look: { coat: '#2f5a3a', coat2: '#437a50', beard: true, chain: true, hair: '#3a2a1a', hairStyle: 5, sk: 1, pants: '#231a2c' },
    hi: { tr: 'Bir uskumru, bir de nasihat: balık taze, söz tatlı olacak!', en: 'One mackerel and some advice: keep the fish fresh and the words sweet!' },
    bye: { tr: 'Yolun açık olsun, tezgâh! Ağın bereketli!', en: 'Safe travels, stall! May your nets be full!' } },
  { id: 'ibo', n: { tr: 'Uzun Hava Ulvi', en: 'Ballad Ulvi' }, sfx: 'sing', fav: 'uskumru', job: { tr: 'Türkü sanatçısı', en: 'Folk singer' },
    trait: { tr: 'Mikrofonunu hiç bırakmaz; kuyrukta uzun hava okur.', en: 'Never lets go of his mic; sings long ballads in line.' },
    fx: '♪', fxc: '#ffd76a', pat: 190,
    look: { belly: 1, coat: '#1f5a5a', coat2: '#2f7a78', must: true, mic: true, cap: '#3a2a1a', hair: '#161010', hairStyle: 0, sk: 2, pants: '#2a1c18' },
    hi: { tr: 'Aaah… bir uskumru ver de türküm yarım kalmasın!', en: 'Aaah… give me a mackerel so my ballad isn\'t left unfinished!' },
    bye: { tr: 'Bu türkü de sana gelsin, balıkçı!', en: 'This next ballad\'s for you, fishmonger!' } },
  { id: 'ayda', n: { tr: 'Işıltı Hanım', en: 'Madame Glimmer' }, sfx: 'sing', fav: 'somon', job: { tr: 'Diva', en: 'Diva' },
    trait: { tr: 'Yavaş yürür, yelpazesini hiç kapatmaz; sabrı kısa ama cömert.', en: 'Walks slowly, never closes her fan; short-tempered but generous.' },
    fx: '✦', fxc: '#ffd76a', pat: 110, tip: 1.7,
    look: { coat: '#1f3f6b', coat2: '#335a92', sash: '#e8d6a0', glasses: true, hair: '#8a2a4a', hairStyle: 6, sk: 0, skirt: '#16284a' },
    hi: { tr: 'Bana bu sabah tutulmuşunu verin, tatlım.', en: 'Give me this morning\'s catch, darling.' },
    bye: { tr: 'Mükemmel… size bir şarkı borçluyum!', en: 'Perfect… I owe you a song!' } },
  { id: 'adnan', n: { tr: 'Reyting Rıfat', en: 'Ratings Rifat' }, sfx: 'fanfare', fav: 'palamut', job: { tr: 'TV yapımcısı', en: 'TV producer' },
    trait: { tr: 'Her şeyi yarışmaya çevirir; kameralar için toplu sipariş verir.', en: 'Turns everything into a game show; bulk-orders for the cameras.' },
    qty: [6, 9], fx: '$', fxc: '#8ef2a2',
    look: { belly: 1, coat: '#6a4a1f', coat2: '#8a6630', phone: true, glasses: true, hair: '#3a2f28', hairStyle: 1, sk: 1, pants: '#1a2433' },
    hi: { tr: 'Bu tezgâhı canlı yayına alıyorum! "Büyük Balık Yarışması" başlasın!', en: 'This stall goes live! Let "The Great Fish Contest" begin!' },
    bye: { tr: 'Reytingler tavan, kardeşim!', en: 'Ratings through the roof, brother!' } },
  { id: 'hoca', n: { tr: 'Nasır Hoca', en: 'Hodja Nasir' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Göl mayalayıcı', en: 'Lake-yogurt maker' },
    trait: { tr: 'Göle maya çalmaya gider; ters mantıklı ama hep haklı çıkar. (Halk fıkralarının kahramanı.)', en: 'Tries to turn a lake into yogurt; backwards logic, always right. (A folk-tale hero.)' },
    fx: '?', fxc: '#f0ece0', pat: 200,
    look: { belly: 1, coat: '#3f6a3a', coat2: '#56884f', turban: '#f0ece0', beard: true, sash: '#c9a15e', hair: '#d8d8d0', hairStyle: 0, sk: 1, pants: '#2e3d28' },
    hi: { tr: 'Göle maya çaldım… ya tutarsa? Tutmadı, balık alayım.', en: 'I put yogurt in the lake… what if it works? It didn\'t. Fish, then.' },
    bye: { tr: 'Ye kürküm ye… pardon, ye balığım ye!', en: 'Eat, my coat, eat… sorry, eat, my fish!' } },
  { id: 'fahri', n: { tr: 'Taktik Tahsin', en: 'Tactics Tahsin' }, sfx: 'whistle', fav: 'levrek', job: { tr: 'Teknik direktör', en: 'Football manager' },
    trait: { tr: 'Tezgâhı taktik tahtasına çevirir; sabırsız ama kral gibi bahşiş verir.', en: 'Treats your stall like a tactics board; impatient, tips like a king.' },
    fx: '!', fxc: '#ff9b8a', pat: 90, tip: 1.6,
    look: { coat: '#1f4a2a', coat2: '#2f6a3c', scarf: '#e6b93a', cap: '#1f4a2a', hair: '#5a4a3a', hairStyle: 0, sk: 1, pants: '#1c1f26' },
    hi: { tr: 'Bu balığı bir de benim sistemimde görün!', en: 'Watch this fish in MY system!' },
    bye: { tr: 'Kazandık! Mağlubiyet yok, sadece hamsi var!', en: 'We won! No defeat, only anchovies!' } },
  { id: 'muslum', n: { tr: 'Hüzünlü Hikmet', en: 'Mournful Hikmet' }, sfx: 'sigh', fav: 'uskumru', job: { tr: 'Arabesk sanatçısı', en: 'Arabesque singer' },
    trait: { tr: 'Her balıkta bir dert bulur; ağlarken bile alışverişini yapar.', en: 'Finds sorrow in every fish; shops even while crying.' },
    fx: '~', fxc: '#8fc0ff',
    look: { coat: '#4a2a2a', coat2: '#643a3a', beard: true, hair: '#161010', hairStyle: 2, sk: 1, pants: '#1c1c22' },
    hi: { tr: 'Kasalar dolu, gönlüm boş… bir uskumru, bir de gözyaşı.', en: 'Crates full, heart empty… one mackerel, one tear.' },
    bye: { tr: 'Hayat bu… bazen hamsi, bazen hüzün.', en: 'That\'s life… sometimes fish, sometimes sorrow.' } },
  { id: 'nazik', n: { tr: 'Kibar Kâmuran', en: 'Courteous Kamuran' }, sfx: 'chime', fav: 'levrek', job: { tr: 'Opera tenoru', en: 'Opera tenor' },
    trait: { tr: 'Aşırı kibar; "efendim" demeden cümle kurmaz. Frakı jilet gibi.', en: 'Impossibly polite; every sentence ends in "sir". Razor-sharp tailcoat.' },
    fx: '✦', fxc: '#dfe6ff', tip: 1.4,
    look: { coat: '#1d1d24', coat2: '#34343f', bowtie: '#f4f0e6', must: true, hair: '#9a9a92', hairStyle: 1, sk: 0, pants: '#1d1d24' },
    hi: { tr: 'Muhterem efendim, bu nadide levrekten lütfeder misiniz?', en: 'Most esteemed sir, might I have this exquisite sea bass?' },
    bye: { tr: 'Hürmetlerimle efendim. Operada görüşmek üzere.', en: 'My deepest respects, sir. See you at the opera.' } },
  { id: 'cuneyt', n: { tr: 'Tekme Tarık', en: 'High-kick Tarik' }, sfx: 'kick', fav: 'palamut', job: { tr: 'Aksiyon yıldızı', en: 'Action star' },
    trait: { tr: 'Kasaları uçan tekmeyle taşır; hızlı iş ister.', en: 'Moves crates with flying kicks; wants it quick.' },
    fx: '!', fxc: '#ffb27a', pat: 100, dance: true,
    look: { tall: 1, coat: '#2a3a5a', coat2: '#3a5078', headband: '#e6b93a', hair: '#3a2a1a', hairStyle: 7, sk: 1, pants: '#2a2018' },
    hi: { tr: 'Hiyaaa! Bir kasa palamut, tek hamlede!', en: 'Hi-yaaa! One crate of bonito, in one move!' },
    bye: { tr: 'Kötüleri yendim, sıra akşam yemeğinde!', en: 'Beat the bad guys — dinner\'s next!' } },
  { id: 'hulya', n: { tr: 'Neşeli Nesrin', en: 'Cheery Nesrin' }, sfx: 'kiss', fav: 'somon', job: { tr: 'Talk show sunucusu', en: 'Talk show host' },
    trait: { tr: 'Herkese iltifat eder, sohbeti bitmez; sabrı uzun.', en: 'Compliments everyone, never stops chatting; very patient.' },
    fx: '♥', fxc: '#ffb0c8', pat: 220,
    look: { coat: '#2f8f7a', coat2: '#43ab94', hair: '#5a2a1a', hairStyle: 3, sk: 1, skirt: '#1f4a40' },
    hi: { tr: 'Ay bu tezgâh ne güzel olmuş, canım benim!', en: 'Oh my, what a gorgeous stall, sweetie!' },
    bye: { tr: 'Öpüyorum hepinizi, bir sonraki programda görüşürüz!', en: 'Kisses to all of you, see you next show!' } },
  { id: 'haluk', n: { tr: 'Yardımsever Yiğit', en: 'Kind-hearted Yigit' }, sfx: 'guitar', fav: 'hamsi', job: { tr: 'Yardımsever rockçı', en: 'Charity rocker' },
    trait: { tr: 'Fazlasını ihtiyaç sahiplerine dağıtır; çok büyük alır.', en: 'Gives the extra to people in need; buys big.' },
    qty: [7, 10], fx: '♥', fxc: '#8ef2a2',
    look: { coat: '#7a2a1f', coat2: '#963a2c', cap: '#1d1d24', guitar: '#8a4a22', hair: '#3a2a1a', hairStyle: 0, sk: 1, pants: '#1f2a36' },
    hi: { tr: 'Fazla ne varsa verin, mahallede dağıtacağız!', en: 'Give me all the extra — we\'ll hand it out in the neighbourhood!' },
    bye: { tr: 'İyilik bulaşıcıdır, sen de bulaş!', en: 'Kindness is contagious — catch it!' } },
  { id: 'berk', n: { tr: 'Kocaman Kaan', en: 'Big-Portion Kaan' }, sfx: 'laugh', fav: 'ton', job: { tr: 'Sosyal medya aşçısı', en: 'Viral food creator' },
    trait: { tr: 'Her lokmada kameraya kocaman bir "Mmm!" yapar; dev porsiyon ister.', en: 'Gives the camera a huge "Mmm!" with every bite; wants giant portions.' },
    qty: [8, 12], fx: '✦', fxc: '#ffffff',
    look: { tall: 1, coat: '#c8553d', coat2: '#e06a50', apron: '#f4f0e6', phone: true, hair: '#161010', hairStyle: 5, sk: 2, pants: '#1a1a1a' },
    hi: { tr: 'Selam millet! Bugün dev bir ton balığı pişiriyoruz!', en: 'Hey everyone! Today we cook a giant tuna!' },
    bye: { tr: 'Abone olmayı unutmayın! Mmm!', en: 'Don\'t forget to subscribe! Mmm!' } },
  { id: 'nurettin', n: { tr: 'Biberci Bülent', en: 'Pepper-spin Bulent' }, sfx: 'sizzle', fav: 'ton', job: { tr: 'Şov aşçısı', en: 'Showman chef' },
    trait: { tr: 'Biber değirmenini havada döndürür; bahşişi de şov gibi.', en: 'Spins the pepper mill in the air; tips like a show.' },
    fx: '·', fxc: '#ffffff', tip: 1.7,
    look: { coat: '#7a1f1f', coat2: '#962c2c', apron: '#2a2a2a', must: true, hair: '#161010', hairStyle: 0, sk: 1, pants: '#141414' },
    hi: { tr: 'Biberi havada çeviririz, balığı gözden seçeriz.', en: 'We spin the pepper in the air and pick the fish by eye.' },
    bye: { tr: '(Biber değirmenini havada döndürür) Ooo, çok şık!', en: '(Spins the pepper mill mid-air) Ooh, very chic!' } },
  { id: 'temel', n: { tr: 'Temel', en: 'Temel' }, sfx: 'whistle', fav: 'hamsi', job: { tr: 'Karadenizli fıkra kahramanı', en: 'Black Sea joke hero' },
    trait: { tr: 'Hamsisiz yapamaz; hep Dursun\'a da götürür. (Halk fıkralarının kahramanı.)', en: 'Can\'t live without anchovies; always brings some to Dursun. (A folk-joke hero.)' },
    qty: [6, 9],
    look: { coat: '#1f4e6b', coat2: '#2f6b8f', knit: '#cfe3f0', beanie: '#1a1a1a', thickMust: true, hair: '#161010', hairStyle: 0, sk: 0, pants: '#2b3a45' },
    hi: { tr: 'Uşağum, hamsi yoksa hayat da yoktur!', en: 'Lad, no anchovies, no life!' },
    bye: { tr: 'Dursun\'a da bir kasa, hadi eyvallah!', en: 'One crate for Dursun too — cheers!' } },

  /* ---------- DÜNYADAN MİSAFİRLER — liman turuna gelen renkli tipler (hepsi özgün karakterdir) ---------- */
  { id: 'gordon', n: { tr: 'Öfkeli Ömer', en: 'Fuming Omer' }, sfx: 'kick', fav: 'levrek', job: { tr: 'Öfkeli şef', en: 'Furious chef' },
    trait: { tr: 'Önce bağırır, sonra tadına bakar; beğenirse çok iyi öder.', en: 'Shouts first, tastes second; pays very well if impressed.' },
    fx: '!', fxc: '#ff6b5a', pat: 90, tip: 1.8,
    look: { coat: '#f4f4f0', coat2: '#ffffff', chefHat: true, apron: '#2a2a2a', thickMust: true, hair: '#3a2a1a', hairStyle: 0, sk: 1, pants: '#2a2a2a' },
    hi: { tr: 'Bu balık… BU BALIK… mükemmel. Neden bağırdım bilmiyorum.', en: 'This fish… THIS FISH… is perfect. No idea why I shouted.' },
    bye: { tr: 'Tamam. Bugün kimse mutfaktan kovulmuyor.', en: 'Fine. Nobody gets kicked out of the kitchen today.' } },
  { id: 'elvin', n: { tr: 'Pomadlı Polat', en: 'Pompadour Polat' }, sfx: 'guitar', fav: 'somon', job: { tr: 'Eski usul rock\'n\'roll\'cu', en: 'Old-school rock\'n\'roller' },
    trait: { tr: 'Saç jölesi hiç bitmez; kuyrukta dizlerini titreterek dans eder.', en: 'Never runs out of hair gel; dances in the queue with wobbly knees.' },
    fx: '♪', fxc: '#ffd76a', dance: true,
    look: { coat: '#2f8f8a', coat2: '#43aba5', bowtie: '#1d1d24', hair: '#161010', hairStyle: 8, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Ooo bebeğim… bir kova somon, ritimle!', en: 'Ooh baby… a bucket of salmon, with rhythm!' },
    bye: { tr: 'Ritim sende, balıkçı!', en: 'You\'ve got the rhythm, fishmonger!' } },
  { id: 'ferdi', n: { tr: 'Koro Kerem', en: 'Chorus Kerem' }, sfx: 'eyo', fav: 'palamut', job: { tr: 'Rock operası solisti', en: 'Rock opera frontman' },
    trait: { tr: 'Kuyrukta bütün limana "Hoop-la!" dedirtir.', en: 'Gets the whole harbour shouting "Hoop-la!" from the queue.' },
    fx: '♪', fxc: '#ffe27a', dance: true, pat: 190,
    look: { coat: '#b3242a', coat2: '#d03a40', beard: true, hair: '#3a2a1a', hairStyle: 5, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Hoop-laaa! Bir palamut, lütfen!', en: 'Hoop-laaa! One bonito, please!' },
    bye: { tr: 'Bu liman bir sahne, siz de korosunuz!', en: 'This harbour\'s a stage and you\'re my choir!' } },
  { id: 'fasulye', n: { tr: 'Sessiz Suat', en: 'Silent Suat' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Sessiz tuhaf adam', en: 'Silent odd fellow' },
    trait: { tr: 'Neredeyse hiç konuşmaz; "Hmm!" der, cebindeki lastik ördeğe danışır.', en: 'Barely speaks; goes "Hmm!" and consults the rubber duck in his pocket.' },
    fx: '?', fxc: '#ffd76a',
    look: { coat: '#4a6a4a', coat2: '#608a60', bowtie: '#e6b93a', beanie: '#c8553d', hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#3a3226' },
    hi: { tr: 'Hmm? …Hmm!', en: 'Hmm? …Hmm!' },
    bye: { tr: '(Lastik ördeğine balığı gösterir) Vak!', en: '(Shows the fish to his rubber duck) Quack!' } },
  { id: 'serlok', n: { tr: 'Şerlok Holmez', en: 'Shirlock Holmz' }, sfx: 'hmm', fav: 'uskumru', job: { tr: 'Dedektif', en: 'Detective' },
    trait: { tr: 'Balığa bakıp nerede, ne zaman tutulduğunu söyler. (Klasik romanlardan esinli.)', en: 'Deduces where and when a fish was caught at a glance. (Inspired by classic novels.)' },
    fx: '?', fxc: '#c9a15e',
    look: { tall: 1, coat: '#7a6a4a', coat2: '#94835e', cap: '#8a7a55', pipe: true, hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#3a3226' },
    hi: { tr: 'Basit, sevgili tezgâhtar: bu balık bu sabah 6.14\'te tutulmuş.', en: 'Elementary, dear vendor: caught this morning at 6:14.' },
    bye: { tr: 'Dava kapandı. Balık da paketlendi.', en: 'Case closed. Fish wrapped.' } },
  { id: 'sinap', n: { tr: 'Sakin Selim', en: 'Mellow Selim' }, sfx: 'drum', fav: 'somon', job: { tr: 'Rahat rapçi', en: 'Laid-back rapper' },
    trait: { tr: 'Çok yavaş ve rahat konuşur; hiç acelesi yoktur.', en: 'Talks slow and chill; never in a hurry.' },
    fx: '♪', fxc: '#8ef2a2', pat: 280,
    look: { tall: 1, coat: '#e6b93a', coat2: '#f0cf5a', cap: '#1d1d24', chain: true, hair: '#161010', hairStyle: 0, sk: 3, pants: '#1f2a36' },
    hi: { tr: 'Yooo… taze mi bu balık? Aceleye gerek yok…', en: 'Yooo… this fish fresh? No rush…' },
    bye: { tr: 'Rahatına bak, balıkçı kardeş.', en: 'Stay easy, fish bro.' } },
  { id: 'kaya', n: { tr: 'Güçlü Güven', en: 'Mighty Guven' }, sfx: 'drum', fav: 'ton', job: { tr: 'Güreşçi-oyuncu', en: 'Wrestler-actor' },
    trait: { tr: 'Kasayı tek eliyle taşır; kaslarını gösterip çok alır.', en: 'Carries a crate in one hand; flexes and buys a lot.' },
    qty: [8, 12],
    look: { tall: 1, coat: '#3a5a2a', coat2: '#4f783a', headband: '#c8553d', beard: true, hair: '#3a2a1a', hairStyle: 0, sk: 2, pants: '#2a2a33' },
    hi: { tr: 'Bu kasa hafif mi? Bana ikisini ver!', en: 'This crate light? Give me two!' },
    bye: { tr: 'İşte bu! Pazılar da onaylıyor.', en: 'That\'s it! The biceps approve.' } },
  { id: 'arnavut', n: { tr: 'Robotik Rüştü', en: 'Robo Rustu' }, sfx: 'robot', fav: 'hamsi', job: { tr: 'Emekli fabrika ustası', en: 'Retired factory foreman' },
    trait: { tr: 'Robot gibi konuşur; her gün tam aynı saatte gelir.', en: 'Talks like a robot; shows up at exactly the same time every day.' },
    look: { tall: 1, coat: '#5a6470', coat2: '#737e8a', vest: '#e6b93a', glasses: true, hair: '#9a9a92', hairStyle: 0, sk: 0, pants: '#2e343c' },
    hi: { tr: 'Bir kasa hamsi. Hemen. İşlem başlatıldı.', en: 'One crate of anchovies. Now. Process started.' },
    bye: { tr: 'Görev tamamlandı. Yarın aynı saatte.', en: 'Task complete. Same time tomorrow.' } },
  { id: 'teylan', n: { tr: 'Şarkıcı Şirin', en: 'Songbird Shirin' }, sfx: 'sing', fav: 'levrek', job: { tr: 'Pop prensesi', en: 'Pop princess' },
    trait: { tr: 'Her alışveriş hakkında şarkı yazar; hayranları peşinde.', en: 'Writes a song about every purchase; fans follow her everywhere.' },
    fx: '♥', fxc: '#ff8fb0',
    look: { coat: '#7a3a8a', coat2: '#9450a6', hair: '#2a1a12', hairStyle: 3, sk: 1, skirt: '#3a1a4a' },
    hi: { tr: 'Bu levrek hakkında da bir şarkı yazacağım.', en: 'I\'m writing a song about this sea bass.' },
    bye: { tr: 'Bu alışveriş de albüme girdi!', en: 'This purchase just made the album!' } },
  { id: 'opra', n: { tr: 'Cömert Cemile', en: 'Generous Cemile' }, sfx: 'fanfare', fav: 'somon', job: { tr: 'Talk show kraliçesi', en: 'Talk show queen' },
    trait: { tr: 'Kuyruktaki herkese balık ısmarlar!', en: 'Buys fish for everyone in the queue!' },
    qty: [10, 14], tip: 1.3, fx: '$', fxc: '#ffd76a',
    look: { belly: 1, coat: '#c8553d', coat2: '#e06a50', scarf: '#e6b93a', scarfDots: '#c8553d', hair: '#161010', hairStyle: 0, sk: 2, skirt: '#5a2a1a' },
    hi: { tr: 'Herkes dinlesin: bugün balıklar benden!', en: 'Listen up, everyone: the fish are on me today!' },
    bye: { tr: 'Hepinize bir kasa, benden olsun!', en: 'A crate for all of you — on me!' } },
  { id: 'mikail', n: { tr: 'Dansçı Deniz', en: 'Dancer Deniz' }, sfx: 'eyo', fav: 'palamut', job: { tr: 'Dans hocası', en: 'Dance teacher' },
    trait: { tr: 'Kuyruğa geri geri kayarak gelir; her adımı sayar.', en: 'Glides into the queue backwards, counting every step.' },
    fx: '✦', fxc: '#ffffff', moon: true,
    look: { coat: '#2f6f9f', coat2: '#4388bb', beanie: '#1d1d24', hair: '#161010', hairStyle: 3, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Adım, adım, kay… bir palamut, lütfen!', en: 'Step, step, glide… one bonito, please!' },
    bye: { tr: '(Geri geri kayarak gider) Beş, altı, yedi, sekiz!', en: '(Glides away backwards) Five, six, seven, eight!' } },
  { id: 'bobros', n: { tr: 'Fırça Ferit', en: 'Brushstroke Ferit' }, sfx: 'chime', fav: 'uskumru', job: { tr: 'Televizyon ressamı', en: 'TV painter' },
    trait: { tr: 'Sakin mi sakin; her lekeden bir dalga, her dalgadan bir tablo çıkarır.', en: 'Serenely calm; turns every smudge into a wave, every wave into a painting.' },
    fx: '✦', fxc: '#8fd8ff', pat: 280,
    look: { coat: '#c8a24a', coat2: '#dcb860', glasses: true, beanie: '#1d1d24', hair: '#9a9a92', hairStyle: 0, sk: 1, pants: '#2e3a4a' },
    hi: { tr: 'Bir uskumru… bir de deniz mavisi. Tuval hazır.', en: 'One mackerel… and a touch of sea blue. Canvas ready.' },
    bye: { tr: 'Her lekeden bir dalga olur.', en: 'Every smudge becomes a wave.' } },
  { id: 'jami', n: { tr: 'Limoncu Levent', en: 'Lemon-squeeze Levent' }, sfx: 'sizzle', fav: 'levrek', job: { tr: 'Genç şef', en: 'Cheeky young chef' },
    trait: { tr: 'Her şeye bir tutam zeytinyağı, bir sıkım limon; koşarak gelir.', en: 'A drizzle of olive oil and a squeeze of lemon on everything; arrives at a jog.' },
    fx: '·', fxc: '#c8e07a',
    look: { coat: '#6a8a3a', coat2: '#82a64c', apron: '#e8eef4', hair: '#5a3a22', hairStyle: 5, sk: 1, pants: '#2a3a4a' },
    hi: { tr: 'Bir tutam zeytinyağı, bir sıkım limon… şahane!', en: 'A drizzle of oil, a squeeze of lemon… gorgeous!' },
    bye: { tr: 'Şahane! Mutfakta görüşürüz!', en: 'Gorgeous! See you in the kitchen!' } },
  { id: 'atinbara', n: { tr: 'Fısıltı Fikret', en: 'Whispering Fikret' }, sfx: 'sigh', fav: 'uskumru', job: { tr: 'Belgesel anlatıcısı', en: 'Nature narrator' },
    trait: { tr: 'Fısıldayarak konuşur; kuyruğu vahşi yaşam belgeseli gibi anlatır.', en: 'Whispers; narrates the queue like a wildlife documentary.' },
    pat: 240,
    look: { coat: '#5a7a4a', coat2: '#6f9460', sunHat: '#c9b48a', glasses: true, hair: '#9a9a92', hairStyle: 0, sk: 1, pants: '#5a4a32' },
    hi: { tr: 'Ve işte… vahşi uskumru, doğal ortamında…', en: 'And here… the wild mackerel, in its natural habitat…' },
    bye: { tr: 'Doğa… ne muhteşem… bir torba daha.', en: 'Nature… how magnificent… one more bag.' } },
  { id: 'cak', n: { tr: 'Demir Yumruk Doğan', en: 'Iron-Fist Dogan' }, sfx: 'kick', fav: 'ton', job: { tr: 'Efsane dövüşçü', en: 'Legendary fighter' },
    trait: { tr: 'Balık tutmaz, balıklar ona teslim olur. Beklemeyi sevmez, parayı fazlasıyla öder.', en: 'Doesn\'t catch fish — fish surrender. Hates waiting, overpays.' },
    fx: '!', fxc: '#ffb27a', pat: 75, tip: 2.0,
    look: { coat: '#1d1d24', coat2: '#34343f', headband: '#b3242a', must: true, sash: '#1d1d24', hair: '#161010', hairStyle: 4, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Ben sıraya girmem. Sıra bana girer.', en: 'I don\'t wait in line. The line waits for me.' },
    bye: { tr: 'Bu tezgâh artık güvende.', en: 'This stall is now safe.' } },
  { id: 'gigi', n: { tr: 'Pullu Pınar', en: 'Sequin Pinar' }, sfx: 'camera', fav: 'uskumru', job: { tr: 'Avangart modacı', en: 'Avant-garde designer' },
    trait: { tr: 'Balık pulundan elbise diker ve giyer. Evet, gerçekten.', en: 'Sews and wears dresses made of fish scales. Yes, really.' },
    fx: '✦', fxc: '#dfe6ff', tip: 1.4,
    look: { coat: '#8fa9bd', coat2: '#b0c6d6', scales: '#5f7f96', glasses: true, hair: '#2a8a8a', hairStyle: 6, sk: 1, skirt: '#6f8fa8' },
    hi: { tr: 'Bu elbiseye bir uskumru daha lazım, darling!', en: 'This dress needs one more mackerel, darling!' },
    bye: { tr: 'Pul pul, parıl parıl! Moda harikası!', en: 'Scales and sparkles! Fashion miracle!' } },
  { id: 'edsirin', n: { tr: 'Kızıl Kenan', en: 'Ginger Kenan' }, sfx: 'guitar', fav: 'palamut', job: { tr: 'Sokak şarkıcısı', en: 'Street songwriter' },
    trait: { tr: 'Gitarıyla gelir, her tezgâha bir aşk şarkısı söyler.', en: 'Shows up with his guitar and sings each stall a love song.' },
    fx: '♪', fxc: '#ffb27a',
    look: { coat: '#3a5a7a', coat2: '#4f7496', beanie: '#6a8a3a', guitar: '#b06a2a', hair: '#c2552a', hairStyle: 1, sk: 0, pants: '#2a3a4a' },
    hi: { tr: 'Gitarım hazır… bu palamuda bir şarkı yazdım.', en: 'Guitar\'s ready… I wrote this bonito a song.' },
    bye: { tr: 'Bu şarkının nakaratı sensin, palamut!', en: 'You\'re the chorus of this song, bonito!' } },

  /* ---------- KOMİK MESLEKLER ---------- */
  { id: 'mahmut', n: { tr: 'Mahmut', en: 'Mahmut the Gull Tamer' }, sfx: 'gull', fav: 'hamsi', job: { tr: 'Martı terbiyecisi', en: 'Seagull trainer' },
    trait: { tr: 'Omzunda martısıyla gezer; aldığının yarısı martıya.', en: 'Walks around with a gull on his shoulder; half of it goes to the bird.' },
    qty: [5, 8], fx: '~', fxc: '#ffffff',
    look: { coat: '#3a6a8a', coat2: '#5084a6', bird: '#f4f4f0', cap: '#23384a', must: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2b3a45' },
    hi: { tr: 'Kaptan Martı bugün aç, en tazesinden!', en: 'Captain Gull is hungry today — the freshest!' },
    bye: { tr: 'Martı onayladı: "Gak!"', en: 'The gull approves: "Squawk!"' } },
  { id: 'sabri', n: { tr: 'Sabri', en: 'Patient Sabri' }, sfx: 'sigh', fav: 'uskumru', job: { tr: 'Profesyonel sıra bekleyici', en: 'Professional queue-sitter' },
    trait: { tr: 'Başkaları yerine sırada bekler; sabrı sonsuz.', en: 'Waits in line for other people; infinite patience.' },
    pat: 420,
    look: { short: 1, belly: 1, coat: '#8a7a5a', coat2: '#a4946f', sunHat: '#e8dcb8', bag: true, hair: '#6f604b', hairStyle: 4, sk: 1, pants: '#4a4232' },
    hi: { tr: 'Acele yok. Ben işimi yapıyorum: beklemek.', en: 'No rush. I\'m doing my job: waiting.' },
    bye: { tr: 'Bugün 14 sırada bekledim, rekor!', en: 'Fourteen queues today — a record!' } },
  { id: 'bedia', n: { tr: 'Bedia Abla', en: 'Sister Bedia' }, sfx: 'chime', fav: 'levrek', job: { tr: 'Balık pulu falcısı', en: 'Fish-scale fortune teller' },
    trait: { tr: 'Fala balık pulunda bakar; tezgâhına bereket okur.', en: 'Reads fortunes in fish scales; blesses your stall.' },
    fx: '✦', fxc: '#d0a0ff', rep: 6,
    look: { belly: 1, coat: '#5a2a6a', coat2: '#743e88', scarf: '#8a3aa8', scarfDots: '#ffd76a', chain: true, bigBag: '#3a1a4a', hair: '#161010', sk: 1, skirt: '#2a1a3a' },
    hi: { tr: 'Pulunda bir yol görüyorum… ve bir kasa levrek.', en: 'I see a journey in your scales… and a crate of sea bass.' },
    bye: { tr: 'Yolun açık, tezgâhın bereketli olsun!', en: 'Clear roads and full crates to you!' } },
  { id: 'recep', n: { tr: 'Tek Göz Recep', en: 'One-Eyed Renny' }, sfx: 'parrot', fav: 'somon', job: { tr: 'Emekli korsan', en: 'Retired pirate' },
    trait: { tr: 'Göz bandı, omzunda papağan; ödemeyi altınla yapar.', en: 'Eyepatch, parrot on shoulder; pays in gold.' },
    fx: '$', fxc: '#ffd76a', tip: 1.6,
    look: { belly: 1, coat: '#8d2a2a', coat2: '#a8403a', tophat: '#1a1a1a', eyepatch: true, beard: true, bird: '#3aa84a', sash: '#d9a441', hair: '#161010', hairStyle: 2, sk: 1, pants: '#2a2018' },
    hi: { tr: 'Yo-ho-ho! Bir sandık somon, tayfa!', en: 'Yo-ho-ho! A chest of salmon, crew!' },
    bye: { tr: 'Hazine bu tezgâhta saklıymış, arrr!', en: 'So the treasure was in this stall, arrr!' } },
  { id: 'miril', n: { tr: 'Mırıl Bey', en: 'Mr. Purrington' }, sfx: 'meow', fav: 'hamsi', job: { tr: 'Kedi sendikası başkanı', en: 'Cat union president' },
    trait: { tr: 'Limanın kedileri adına toplu alım yapar. Pazarlık yok.', en: 'Buys in bulk on behalf of the harbour cats. No haggling.' },
    qty: [9, 12], fx: '♥', fxc: '#ffd0a0',
    look: { coat: '#d08a3a', coat2: '#e8a452', vest: '#3a2f28', bowtie: '#1d1d24', glasses: true, notebook: true, hair: '#9a6a3a', hairStyle: 1, sk: 0, pants: '#3a2f28' },
    hi: { tr: 'Sendikamız adına: 40 kedi, 40 hamsi. Pazarlık yok!', en: 'On behalf of the union: 40 cats, 40 anchovies. No haggling!' },
    bye: { tr: 'Miyav. Yani… teşekkürler.', en: 'Meow. I mean… thank you.' } },
  { id: 'selin', n: { tr: 'Selfi Selin', en: 'Selfie Selin' }, sfx: 'camera', fav: 'somon', job: { tr: 'Fenomen', en: 'Influencer' },
    trait: { tr: 'Almadan önce otuz selfie çeker; ışığı beğenmezse bekler.', en: 'Takes thirty selfies first; waits if the light is wrong.' },
    fx: '✦', fxc: '#ffffff', pat: 180, rep: 5,
    look: { coat: '#f08ab0', coat2: '#ffa8c8', shades: true, phone: true, hair: '#e07aa8', hairStyle: 3, sk: 0, skirt: '#3a2a4a' },
    hi: { tr: 'Dur dur, önce bir selfie! Işık süper!', en: 'Wait wait, selfie first! The light is amazing!' },
    bye: { tr: 'Hikâyeye attım, sen de fenomen oldun!', en: 'Posted it — you\'re famous now!' } }
];
