/* =====================================================================
   HAMSİ KOYU — ÖZEL İSİMLİ MÜŞTERİLER  (bu dosyayı serbestçe düzenle)
   ---------------------------------------------------------------------
   Her gün havuzdan 2 kişi gelir (dün gelenler ertesi gün tekrar gelmez).
   Yeni kişi eklemek = listeye yeni bir { ... } bloğu eklemek. Silmek = bloğu silmek.
   Tüm karakterler özgündür; gerçek kişilerle herhangi bir benzerlik tesadüftür.
   KURAL (mağaza yayını): gerçek, yaşayan ya da yakın zamanda ölmüş ünlülerin adını, lakabını, imza sözünü,
   şarkı sözünü veya tanınır görünüşünü kullanma. Halk fıkrası kahramanları (Temel, Nasreddin Hoca) serbesttir.

   ZORUNLU ALANLAR
     id    : benzersiz kısa kimlik (küçük harf, boşluksuz)   örn. 'temel'
     n     : ekranda görünen isim — tek dil 'Temel' ya da iki dil { tr: 'Tek Göz Recep', en: 'One-Eyed Renny' }
     job   : meslek          { tr: '...', en: '...' }  (ya da tek dilde 'metin')
     hi    : kuyruğa girince söylediği   { tr, en }
     bye   : mutlu ayrılırken söylediği  { tr, en }
     me    : ilk gelişte kendini tanıtması (önce bu, sonra hi). Adı oyuncu ilk siparişini bitirince öğrenir.

   İSTEĞE BAĞLI — KARAKTER
     trait : huyu / özelliği (menü › ALBÜM'de görünür)   { tr, en }
     fav   : sevdiği balık: hamsi | uskumru | palamut | levrek | somon | ton
             (o tezgâh açıksa oraya gider, değilse açık herhangi bir tezgâha)

   İSTEĞE BAĞLI — OYUN ETKİSİ (yazılmazsa varsayılan)
     qty   : sipariş adedi [en az, en çok]          varsayılan [3, 5]
     pat   : sabır (saniye)                          varsayılan 150
     tip   : ödeme çarpanı (1 = normal fiyat)        varsayılan 1.1
     rep   : verdiği itibar                          varsayılan 3
     fx    : başının üstünden uçuşan işaret: '♪' '♥' '✦' '!' '?' '$' '~' '·'
     sfx   : gelince ve mutlu giderken çalan hafif ses:
             hmm chime whistle bell kiss guitar sing eyo laugh sigh kick robot
             gull parrot meow camera cash drum sizzle fanfare
     fxc   : işaretin rengi                          örn. '#ff6b8a'
     moon  : true → geri geri kayarak yürür (moonwalk)
     dance : true → kuyrukta hoplayıp dans eder

   GÖRÜNÜŞ — look: { ... }   (renkler '#rrggbb')
     sk        : ten 0 açık … 3 koyu
     hair      : saç rengi          hairStyle: 0 kısa, 1 dalgalı, 2 uzun, 3 at kuyruğu,
                                               4 kel, 5 kıvırcık/afro, 6 topuz, 7 mohikan, 8 kabarık perçem
     coat/coat2: üst giysi + omuz ışığı     pants: pantolon     skirt: uzun etek (pantolon yerine)
     tall / short / belly : 1 → uzun boy / kısa boy / göbekli
     Başlık (biri): cap, beanie, sunHat, tophat, turban (renk)  ·  fez, chefHat (true)  ·  scarf (başörtüsü, renk) + scarfDots
     Yüz: must, thickMust, beard (true) · glasses, shades (güneş gözlüğü), eyepatch, pipe (true)
     Üst: apron, vest, sash, tie, bowtie, cape (pelerin), scales (balık pulu desenli elbise), knit, headband (renk)
          chain (altın kolye, true)
     Eşya: bag, notebook, mic, phone (true) · bigBag, guitar, bird (omuzda kuş) (renk)
   ===================================================================== */
window.BT_SPECIALS = [

  /* ---------- İLK 10: mahallenin tanıdık yüzleri ---------- */
  { id: 'caner', n: { tr: 'Caner', en: 'Caner' }, me: { tr: 'Ben Caner. Mahallede bana \'Mercek Caner\' derler, gözümden balık kaçmaz.', en: 'I\'m Caner. The street calls me \'Magnifier Caner\'; no fish escapes my eye.' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Kaliteci', en: 'Quality inspector' },
    trait: { tr: 'Her balığı tek tek inceler; kedilere mutlaka pay ayırır.', en: 'Inspects every fish; always saves a share for the cats.' },
    look: { tall: 1, belly: 1, coat: '#5b6d7c', coat2: '#6f8394', hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#33393f' },
    hi: { tr: 'Önce bir bakayım… tamam, bundan alalım.', en: 'Let me take a look… right, I\'ll have this.' },
    bye: { tr: 'Kalitesi yerinde. Kedilere de bir parça ayırdım.', en: 'Quality checks out. Saved a bite for the cats.' } },
  { id: 'pelin', n: { tr: 'Pelin', en: 'Pelin' }, me: { tr: 'Merhaba, ben Pelin. Deniz biyoloğuyum; balıkla önce göz göze gelirim.', en: 'Hi, I\'m Pelin. Marine biologist; I look a fish in the eye first.' }, sfx: 'chime', fav: 'levrek', job: { tr: 'Biyolog', en: 'Biologist' },
    trait: { tr: 'Solungaca bakıp tazeliği saniyede söyler.', en: 'Reads freshness from the gills in a second.' },
    look: { coat: '#3f7f7a', coat2: '#56988f', hair: '#d9772b', hairStyle: 5, sk: 0, pants: '#2b3a45' },
    hi: { tr: 'Gözleri parlak, solungaçlar kırmızı. Güzel.', en: 'Bright eyes, red gills. Good.' },
    bye: { tr: 'Net ve temiz. Teşekkürler.', en: 'Clean and precise. Thank you.' } },
  { id: 'riza', n: { tr: 'Rıza', en: 'Rıza' }, me: { tr: 'Rıza usta ben! Musluk akıtır, ben balık alırım. Herkes \'Anahtar Rıza\' der.', en: 'Rıza the fixer! Taps leak, I buy fish. Everyone calls me \'Wrench Rıza\'.' }, sfx: 'whistle', fav: 'hamsi', job: { tr: 'Tesisat ustası', en: 'Plumber' },
    trait: { tr: 'Sabahın köründe gelir, işe balıkla başlar.', en: 'Shows up at dawn; the day starts with fish.' },
    look: { belly: 1, coat: '#3f5f8f', coat2: '#557aa8', cap: '#2b2b2b', thickMust: true, hair: '#1d1713', hairStyle: 0, sk: 2, pants: '#2e3a4a' },
    hi: { tr: 'Sabahın köründe iş başı, önce balık!', en: 'Up at dawn — fish comes first!' },
    bye: { tr: 'Eline sağlık. Musluk bozulursa bana haber ver.', en: 'Cheers. If a tap leaks, you know who to call.' } },
  { id: 'nermin', n: { tr: 'Nermin', en: 'Nermin' }, me: { tr: 'Ben Nermin öğretmen. Kırk yıl kara tahta, şimdi balık tezgâhı denetliyorum.', en: 'I\'m Mrs. Nermin, teacher. Forty years at the blackboard; now I inspect fish stalls.' }, sfx: 'bell', fav: 'uskumru', job: { tr: 'Emekli öğretmen', en: 'Retired teacher' },
    trait: { tr: 'Tezgâha not verir; düzenliysen bahşişi artar.', en: 'Grades your stall; tidy stalls get a better tip.' },
    tip: 1.25,
    look: { short: 1, belly: 1, coat: '#8a4a6a', coat2: '#a45f82', hair: '#9a9a96', hairStyle: 1, sk: 0, skirt: '#4a3a4a', bigBag: '#6b2f3a' },
    hi: { tr: 'Evladım, bugün hangisi taze?', en: 'Dear, which one is fresh today?' },
    bye: { tr: 'Aferin sana. Hep böyle düzenli ol.', en: 'Well done, dear. Keep it this tidy.' } },
  { id: 'kemal', n: { tr: 'Kemal', en: 'Kemal' }, me: { tr: 'Kemal ben, sahildeki lokanta benim. Mutfakta herkes \'Patron\' der.', en: 'I\'m Kemal, the restaurant on the shore is mine. In the kitchen they call me \'Boss\'.' }, sfx: 'cash', fav: 'levrek', job: { tr: 'Lokanta işletmecisi', en: 'Restaurant owner' },
    trait: { tr: 'Akşam servisi için toplu alır.', en: 'Buys in bulk for the evening service.' },
    qty: [5, 8],
    look: { tall: 1, coat: '#e8e2d2', coat2: '#f4efe4', vest: '#3a2f28', notebook: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2a2724' },
    hi: { tr: 'Akşam servisi için not alıyorum…', en: 'Taking notes for tonight\'s service…' },
    bye: { tr: 'Yarın yine gelirim, masalar dolu.', en: 'Back tomorrow — the tables are full.' } },
  { id: 'sule', n: { tr: 'Şule', en: 'Şule' }, me: { tr: 'Şule ben, terziyim. İğneyle ipliğim gibi, balıkla limonum da ayrılmaz.', en: 'I\'m Şule, a tailor. Like needle and thread, fish and lemon never part.' }, sfx: 'chime', fav: 'uskumru', job: { tr: 'Terzi', en: 'Tailor' },
    trait: { tr: 'Paketin dikişine bile bakar.', en: 'Even checks the seams on the wrapping.' },
    look: { coat: '#7a2b4a', coat2: '#94405f', hair: '#3d2a1a', hairStyle: 6, sk: 0, skirt: '#2f3a5a' },
    hi: { tr: 'Tezgâhın ne kadar derli toplu, beğendim.', en: 'Such a neat stall. I like it.' },
    bye: { tr: 'Paketi de özenli yapmışsın, sağ ol.', en: 'Wrapped with care, too. Thank you.' } },
  { id: 'okan', n: { tr: 'Okan', en: 'Okan' }, me: { tr: 'Okan! Kurye! Adımı söyledim mi? Söyledim. Hadi hadi!', en: 'Okan! Courier! Did I say my name? I did. Come on, come on!' }, sfx: 'bell', fav: 'hamsi', job: { tr: 'Kurye', en: 'Courier' },
    trait: { tr: 'Hep acelesi var; çabuk servis ister.', en: 'Always in a hurry; wants it fast.' },
    pat: 95,
    look: { coat: '#e0a030', coat2: '#f0bd55', bag: true, hair: '#1d1713', hairStyle: 0, sk: 2, pants: '#2b3a45' },
    hi: { tr: 'Çabuk olursak iyi olur, teslimat bekliyor!', en: 'Quick if we can — a delivery\'s waiting!' },
    bye: { tr: 'Hızlı servis, tam benlik!', en: 'Fast service, just my style!' } },
  { id: 'fatos', n: { tr: 'Fatoş', en: 'Fatoş' }, me: { tr: 'Ben Fatoş. Konu komşu \'Buğulamacı Fatoş\' der, tencerem hiç boş kalmaz.', en: 'I\'m Fatoş. The neighbours call me \'Stew Fatoş\'; my pot is never empty.' }, sfx: 'sizzle', fav: 'uskumru', job: { tr: 'Ev aşçısı', en: 'Home cook' },
    trait: { tr: 'Buğulama ustası; herkese bir tabak ayırır.', en: 'Steamed-fish expert; saves everyone a plate.' },
    look: { belly: 1, coat: '#c8553d', coat2: '#dc6d55', scarf: '#e0679e', scarfDots: '#ffd76a', apron: '#f0ece0', hair: '#3d2a1a', sk: 1, skirt: '#5a3f7a' },
    hi: { tr: 'Bu akşam buğulama yapacağım, en tazesinden!', en: 'Steamed fish tonight — the freshest, please!' },
    bye: { tr: 'Afiyetle yiyelim, sana da bir tabak ayırırım!', en: 'Enjoy! I\'ll save you a plate!' } },
  { id: 'burak', n: { tr: 'Burak', en: 'Burak' }, me: { tr: 'Burak, bankacı. Faiz, kur, balık: üçünü de günlük takip ederim.', en: 'Burak, banker. Interest, rates, fish: I track all three daily.' }, sfx: 'cash', fav: 'levrek', job: { tr: 'Bankacı', en: 'Banker' },
    trait: { tr: 'Kuruşu kuruşuna öder, fazlasını değil.', en: 'Pays to the penny, not a penny more.' },
    tip: 1.0,
    look: { coat: '#2f3f5a', coat2: '#43557a', vest: '#e8e2d2', beard: true, tie: '#8d2a2a', hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#252c38' },
    hi: { tr: 'Hesap kitap tamam, şimdi balık zamanı.', en: 'Books are balanced — fish time.' },
    bye: { tr: 'Teşekkürler, iyi işler.', en: 'Thanks. Good business to you.' } },
  { id: 'ayfer', n: { tr: 'Ayfer', en: 'Ayfer' }, me: { tr: 'Eczacı Ayfer ben. Reçetesiz ilaç vermem ama balığı herkese öneririm.', en: 'Ayfer, pharmacist. No pills without prescription, but fish I recommend to all.' }, sfx: 'chime', fav: 'hamsi', job: { tr: 'Eczacı', en: 'Pharmacist' },
    trait: { tr: 'Balığı reçete gibi yazar: haftada iki kez.', en: 'Prescribes fish: twice a week.' },
    look: { coat: '#f0ece0', coat2: '#fbf8f0', glasses: true, hair: '#3d2a1a', hairStyle: 1, sk: 0, pants: '#3a4450' },
    hi: { tr: 'Omega-3 için haftada iki kez balık, reçetem bu.', en: 'Fish twice a week — that\'s my prescription.' },
    bye: { tr: 'Düzenli beslenmek önemli. Görüşürüz.', en: 'Eat regularly. See you soon.' } },

  /* ---------- MEŞHUR TİPLER — sahnenin, ekranın, mutfağın renkli yüzleri (hepsi özgün karakterdir) ---------- */
  { id: 'tarkut', n: { tr: 'Kıvanç Parıltı', en: 'Kivanch Sparkle' }, me: { tr: 'Hayranlarım bana Kıvanç Parıltı der… tamam, gerçek adım da bu! Muah!', en: 'My fans call me Kıvanç Sparkle… fine, it\'s my real name too! Mwah!' }, sfx: 'kiss', fav: 'levrek', job: { tr: 'Pop Megastarı', en: 'Pop megastar' },
    trait: { tr: 'Öpücük atmadan balık almaz; kuyrukta pul pul ceketiyle dans eder.', en: 'Won\'t buy without blowing a kiss; dances in the queue in his sequin jacket.' },
    fx: '♥', fxc: '#ff6b8a', dance: true, tip: 1.4,
    look: { coat: '#5a1f6b', coat2: '#7a3590', chain: true, hair: '#3a1f12', hairStyle: 7, sk: 1, pants: '#1a1a20' },
    hi: { tr: 'Parlayan pullar, parlayan levrek… bir tane lütfen!', en: 'Shiny scales, shiny sea bass… one, please!' },
    bye: { tr: 'Sahnede görüşürüz, tezgâh! Öpücükler!', en: 'See you on stage, stall! Kisses!' } },
  { id: 'cemal', n: { tr: 'Kahkaha Kadir', en: 'Chuckle Kadir' }, me: { tr: 'Kahkaha Kadir! Sahnede espri, tezgâhta balık. İkisi de taze olmalı.', en: 'Laughing Kadir! Jokes on stage, fish at the stall. Both must be fresh.' }, sfx: 'laugh', fav: 'palamut', job: { tr: 'Stand-up komedyeni', en: 'Stand-up comedian' },
    trait: { tr: 'Kuyrukta şov yapar; herkes güldüğü için kimse sabırsızlanmaz.', en: 'Does a set in the queue; everyone laughs, so nobody gets impatient.' },
    fx: '!', fxc: '#ffd76a', pat: 230,
    look: { coat: '#6a3a22', coat2: '#85502e', glasses: true, hair: '#1d1713', hairStyle: 5, sk: 1, pants: '#1f252c' },
    hi: { tr: 'Balıkçıya girdim, balık bana dedi ki: "Abi, sen de mi tuzlusun?"', en: 'I walk into the fish shop and the fish says: "You salty too, pal?"' },
    bye: { tr: 'Harika seyircisiniz! Bahşişler kovaya!', en: 'Great crowd! Tips in the bucket!' } },
  { id: 'sukru', n: { tr: 'Saf Sadık', en: 'Simple Sadik' }, me: { tr: 'Ben Sadık, mahallenin bekçisi. Herkes \'Saf Sadık\' der ama ben gülerim.', en: 'I\'m Sadık, the night watchman. They call me \'Simple Sadık\'; I just smile.' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Mahalle bekçisi', en: 'Night watchman' },
    trait: { tr: 'Saf ama altın kalpli; siparişini iki kez sorar, bahşişi bol.', en: 'Naive with a heart of gold; asks twice, tips big.' },
    tip: 1.5,
    look: { short: 1, coat: '#6b5a3a', coat2: '#85714c', vest: '#3a2f22', cap: '#c9a15e', must: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#3a3226' },
    hi: { tr: 'Ben bi\' şey demedim… balık dedi ki beni al!', en: 'I didn\'t say a thing… the fish said "take me"!' },
    bye: { tr: 'Hıh! Çok şükür, doyduk.', en: 'Heh! Thank goodness, we\'re fed.' } },
  { id: 'barlas', n: { tr: 'Yüzüklü Yavuz', en: 'Ringed Yavuz' }, me: { tr: 'Yavuz derler bana, on parmakta on yüzük. Her birinin bir hikâyesi var.', en: 'They call me Yavuz, ten rings on ten fingers. Each has a story.' }, sfx: 'guitar', fav: 'uskumru', job: { tr: 'Rock ozanı', en: 'Rock bard' },
    trait: { tr: 'Parmakları yüzük dolu; her alışverişte tezgâha bir nasihat bırakır.', en: 'Fingers full of rings; leaves the stall a piece of advice with every purchase.' },
    fx: '♪', fxc: '#c9a0ff',
    look: { coat: '#2f5a3a', coat2: '#437a50', beard: true, chain: true, hair: '#3a2a1a', hairStyle: 5, sk: 1, pants: '#231a2c' },
    hi: { tr: 'Bir uskumru, bir de nasihat: balık taze, söz tatlı olacak!', en: 'One mackerel and some advice: keep the fish fresh and the words sweet!' },
    bye: { tr: 'Yolun açık olsun, tezgâh! Ağın bereketli!', en: 'Safe travels, stall! May your nets be full!' } },
  { id: 'ibo', n: { tr: 'Uzun Hava Ulvi', en: 'Ballad Ulvi' }, me: { tr: 'Ulvi\'yim! Uzun havayı benden uzun okuyan yoktur, nefesim hiç bitmez!', en: 'I\'m Ulvi! Nobody sings the long ballad longer than me; my breath never ends!' }, sfx: 'sing', fav: 'uskumru', job: { tr: 'Türkü sanatçısı', en: 'Folk singer' },
    trait: { tr: 'Mikrofonunu hiç bırakmaz; kuyrukta uzun hava okur.', en: 'Never lets go of his mic; sings long ballads in line.' },
    fx: '♪', fxc: '#ffd76a', pat: 190,
    look: { belly: 1, coat: '#1f5a5a', coat2: '#2f7a78', must: true, mic: true, cap: '#3a2a1a', hair: '#161010', hairStyle: 0, sk: 2, pants: '#2a1c18' },
    hi: { tr: 'Aaah… bir uskumru ver de türküm yarım kalmasın!', en: 'Aaah… give me a mackerel so my ballad isn\'t left unfinished!' },
    bye: { tr: 'Bu türkü de sana gelsin, balıkçı!', en: 'This next ballad\'s for you, fishmonger!' } },
  { id: 'ayda', n: { tr: 'Işıltı Hanım', en: 'Madame Glimmer' }, me: { tr: 'Işıltı Hanım derler bana, tatlım. Sahne ışığı olmasa da parlarım.', en: 'They call me Lady Glimmer, darling. I shine even without stage lights.' }, sfx: 'sing', fav: 'somon', job: { tr: 'Diva', en: 'Diva' },
    trait: { tr: 'Yavaş yürür, yelpazesini hiç kapatmaz; sabrı kısa ama cömert.', en: 'Walks slowly, never closes her fan; short-tempered but generous.' },
    fx: '✦', fxc: '#ffd76a', pat: 110, tip: 1.7,
    look: { coat: '#1f3f6b', coat2: '#335a92', sash: '#e8d6a0', glasses: true, hair: '#8a2a4a', hairStyle: 6, sk: 0, skirt: '#16284a' },
    hi: { tr: 'Bana bu sabah tutulmuşunu verin, tatlım.', en: 'Give me this morning\'s catch, darling.' },
    bye: { tr: 'Mükemmel… size bir şarkı borçluyum!', en: 'Perfect… I owe you a song!' } },
  { id: 'adnan', n: { tr: 'Reyting Rıfat', en: 'Ratings Rifat' }, me: { tr: 'Rıfat, yapımcı! Herkes \'Reyting Rıfat\' der: ben neye bakarsam o tutar!', en: 'Rıfat, producer! They call me \'Ratings Rıfat\': whatever I watch, sells!' }, sfx: 'fanfare', fav: 'palamut', job: { tr: 'TV yapımcısı', en: 'TV producer' },
    trait: { tr: 'Her şeyi yarışmaya çevirir; kameralar için toplu sipariş verir.', en: 'Turns everything into a game show; bulk-orders for the cameras.' },
    qty: [6, 9], fx: '$', fxc: '#8ef2a2',
    look: { belly: 1, coat: '#6a4a1f', coat2: '#8a6630', phone: true, glasses: true, hair: '#3a2f28', hairStyle: 1, sk: 1, pants: '#1a2433' },
    hi: { tr: 'Bu tezgâhı canlı yayına alıyorum! "Büyük Balık Yarışması" başlasın!', en: 'This stall goes live! Let "The Great Fish Contest" begin!' },
    bye: { tr: 'Reytingler tavan, kardeşim!', en: 'Ratings through the roof, brother!' } },
  { id: 'hoca', n: { tr: 'Nasır Hoca', en: 'Hodja Nasir' }, me: { tr: 'Nasır Hoca derler bana. Eşeğimi ters binerim, çünkü yol ters gidiyor.', en: 'They call me Master Nasır. I ride my donkey backwards; the road goes backwards.' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Göl mayalayıcı', en: 'Lake-yogurt maker' },
    trait: { tr: 'Göle maya çalmaya gider; ters mantıklı ama hep haklı çıkar. (Halk fıkralarının kahramanı.)', en: 'Tries to turn a lake into yogurt; backwards logic, always right. (A folk-tale hero.)' },
    fx: '?', fxc: '#f0ece0', pat: 200,
    look: { belly: 1, coat: '#3f6a3a', coat2: '#56884f', turban: '#f0ece0', beard: true, sash: '#c9a15e', hair: '#d8d8d0', hairStyle: 0, sk: 1, pants: '#2e3d28' },
    hi: { tr: 'Göle maya çaldım… ya tutarsa? Tutmadı, balık alayım.', en: 'I put yogurt in the lake… what if it works? It didn\'t. Fish, then.' },
    bye: { tr: 'Ye kürküm ye… pardon, ye balığım ye!', en: 'Eat, my coat, eat… sorry, eat, my fish!' } },
  { id: 'fahri', n: { tr: 'Taktik Tahsin', en: 'Tactics Tahsin' }, me: { tr: 'Tahsin hoca, teknik direktör! Bana \'Taktik\' derler, maçı tezgâhta kazanırım.', en: 'Coach Tahsin! They call me \'Tactics\'; I win matches at the stall.' }, sfx: 'whistle', fav: 'levrek', job: { tr: 'Teknik direktör', en: 'Football manager' },
    trait: { tr: 'Tezgâhı taktik tahtasına çevirir; sabırsız ama kral gibi bahşiş verir.', en: 'Treats your stall like a tactics board; impatient, tips like a king.' },
    fx: '!', fxc: '#ff9b8a', pat: 90, tip: 1.6,
    look: { coat: '#1f4a2a', coat2: '#2f6a3c', scarf: '#e6b93a', cap: '#1f4a2a', hair: '#5a4a3a', hairStyle: 0, sk: 1, pants: '#1c1f26' },
    hi: { tr: 'Bu balığı bir de benim sistemimde görün!', en: 'Watch this fish in MY system!' },
    bye: { tr: 'Kazandık! Mağlubiyet yok, sadece hamsi var!', en: 'We won! No defeat, only anchovies!' } },
  { id: 'muslum', n: { tr: 'Hüzünlü Hikmet', en: 'Mournful Hikmet' }, me: { tr: 'Hikmet derler… hüzünlü olanı. Hayat bir uskumru, ben de kılçığıyım.', en: 'They call me Hikmet… the melancholy one. Life is a mackerel; I\'m its bone.' }, sfx: 'sigh', fav: 'uskumru', job: { tr: 'Arabesk sanatçısı', en: 'Arabesque singer' },
    trait: { tr: 'Her balıkta bir dert bulur; ağlarken bile alışverişini yapar.', en: 'Finds sorrow in every fish; shops even while crying.' },
    fx: '~', fxc: '#8fc0ff',
    look: { coat: '#4a2a2a', coat2: '#643a3a', beard: true, hair: '#161010', hairStyle: 2, sk: 1, pants: '#1c1c22' },
    hi: { tr: 'Kasalar dolu, gönlüm boş… bir uskumru, bir de gözyaşı.', en: 'Crates full, heart empty… one mackerel, one tear.' },
    bye: { tr: 'Hayat bu… bazen hamsi, bazen hüzün.', en: 'That\'s life… sometimes fish, sometimes sorrow.' } },
  { id: 'nazik', n: { tr: 'Kibar Kâmuran', en: 'Courteous Kamuran' }, me: { tr: 'Arz-ı hürmetler efendim, naçizane Kâmuran. Tenorum, kibarlık mesleğim.', en: 'My humblest regards, sir, I am Kâmuran. A tenor; courtesy is my trade.' }, sfx: 'chime', fav: 'levrek', job: { tr: 'Opera tenoru', en: 'Opera tenor' },
    trait: { tr: 'Aşırı kibar; "efendim" demeden cümle kurmaz. Frakı jilet gibi.', en: 'Impossibly polite; every sentence ends in "sir". Razor-sharp tailcoat.' },
    fx: '✦', fxc: '#dfe6ff', tip: 1.4,
    look: { coat: '#1d1d24', coat2: '#34343f', bowtie: '#f4f0e6', must: true, hair: '#9a9a92', hairStyle: 1, sk: 0, pants: '#1d1d24' },
    hi: { tr: 'Muhterem efendim, bu nadide levrekten lütfeder misiniz?', en: 'Most esteemed sir, might I have this exquisite sea bass?' },
    bye: { tr: 'Hürmetlerimle efendim. Operada görüşmek üzere.', en: 'My deepest respects, sir. See you at the opera.' } },
  { id: 'cuneyt', n: { tr: 'Tekme Tarık', en: 'High-kick Tarik' }, me: { tr: 'Tarık! Herkes \'Tekme Tarık\' der. Kapıyı bile tekmeyle açarım. Hiya!', en: 'Tarık! They call me \'Kick Tarık\'. I open doors with a kick. Hiya!' }, sfx: 'kick', fav: 'palamut', job: { tr: 'Aksiyon yıldızı', en: 'Action star' },
    trait: { tr: 'Kasaları uçan tekmeyle taşır; hızlı iş ister.', en: 'Moves crates with flying kicks; wants it quick.' },
    fx: '!', fxc: '#ffb27a', pat: 100, dance: true,
    look: { tall: 1, coat: '#2a3a5a', coat2: '#3a5078', headband: '#e6b93a', hair: '#3a2a1a', hairStyle: 7, sk: 1, pants: '#2a2018' },
    hi: { tr: 'Hiyaaa! Bir kasa palamut, tek hamlede!', en: 'Hi-yaaa! One crate of bonito, in one move!' },
    bye: { tr: 'Kötüleri yendim, sıra akşam yemeğinde!', en: 'Beat the bad guys — dinner\'s next!' } },
  { id: 'hulya', n: { tr: 'Neşeli Nesrin', en: 'Cheery Nesrin' }, me: { tr: 'Ben Nesrin, canım! Ekranda konuşurum, ekran kapanınca da konuşurum!', en: 'I\'m Nesrin, sweetie! I talk on screen, and I talk when it\'s off!' }, sfx: 'kiss', fav: 'somon', job: { tr: 'Talk show sunucusu', en: 'Talk show host' },
    trait: { tr: 'Herkese iltifat eder, sohbeti bitmez; sabrı uzun.', en: 'Compliments everyone, never stops chatting; very patient.' },
    fx: '♥', fxc: '#ffb0c8', pat: 220,
    look: { coat: '#2f8f7a', coat2: '#43ab94', hair: '#5a2a1a', hairStyle: 3, sk: 1, skirt: '#1f4a40' },
    hi: { tr: 'Ay bu tezgâh ne güzel olmuş, canım benim!', en: 'Oh my, what a gorgeous stall, sweetie!' },
    bye: { tr: 'Öpüyorum hepinizi, bir sonraki programda görüşürüz!', en: 'Kisses to all of you, see you next show!' } },
  { id: 'haluk', n: { tr: 'Yardımsever Yiğit', en: 'Kind-hearted Yigit' }, me: { tr: 'Yiğit ben. Gitarım bir elimde, yardım çantam öbüründe.', en: 'I\'m Yiğit. My guitar in one hand, the charity bag in the other.' }, sfx: 'guitar', fav: 'hamsi', job: { tr: 'Yardımsever rockçı', en: 'Charity rocker' },
    trait: { tr: 'Fazlasını ihtiyaç sahiplerine dağıtır; çok büyük alır.', en: 'Gives the extra to people in need; buys big.' },
    qty: [7, 10], fx: '♥', fxc: '#8ef2a2',
    look: { coat: '#7a2a1f', coat2: '#963a2c', cap: '#1d1d24', guitar: '#8a4a22', hair: '#3a2a1a', hairStyle: 0, sk: 1, pants: '#1f2a36' },
    hi: { tr: 'Fazla ne varsa verin, mahallede dağıtacağız!', en: 'Give me all the extra — we\'ll hand it out in the neighbourhood!' },
    bye: { tr: 'İyilik bulaşıcıdır, sen de bulaş!', en: 'Kindness is contagious — catch it!' } },
  { id: 'berk', n: { tr: 'Kocaman Kaan', en: 'Big-Portion Kaan' }, me: { tr: 'Selam millet, Kocaman Kaan burada! Takipçilerim balığını görmek istiyor!', en: 'Hey folks, Big Kaan here! My followers want to see your fish!' }, sfx: 'laugh', fav: 'ton', job: { tr: 'Sosyal medya aşçısı', en: 'Viral food creator' },
    trait: { tr: 'Her lokmada kameraya kocaman bir "Mmm!" yapar; dev porsiyon ister.', en: 'Gives the camera a huge "Mmm!" with every bite; wants giant portions.' },
    qty: [8, 12], fx: '✦', fxc: '#ffffff',
    look: { tall: 1, coat: '#c8553d', coat2: '#e06a50', apron: '#f4f0e6', phone: true, hair: '#161010', hairStyle: 5, sk: 2, pants: '#1a1a1a' },
    hi: { tr: 'Selam millet! Bugün dev bir ton balığı pişiriyoruz!', en: 'Hey everyone! Today we cook a giant tuna!' },
    bye: { tr: 'Abone olmayı unutmayın! Mmm!', en: 'Don\'t forget to subscribe! Mmm!' } },
  { id: 'nurettin', n: { tr: 'Biberci Bülent', en: 'Pepper-spin Bulent' }, me: { tr: 'Bülent! \'Biberci\' derler. Biberi havada döndürürüm, kalbinizi de.', en: 'Bülent! They call me \'Pepper\'. I spin the pepper mill, and your heart.' }, sfx: 'sizzle', fav: 'ton', job: { tr: 'Şov aşçısı', en: 'Showman chef' },
    trait: { tr: 'Biber değirmenini havada döndürür; bahşişi de şov gibi.', en: 'Spins the pepper mill in the air; tips like a show.' },
    fx: '·', fxc: '#ffffff', tip: 1.7,
    look: { coat: '#7a1f1f', coat2: '#962c2c', apron: '#2a2a2a', must: true, hair: '#161010', hairStyle: 0, sk: 1, pants: '#141414' },
    hi: { tr: 'Biberi havada çeviririz, balığı gözden seçeriz.', en: 'We spin the pepper in the air and pick the fish by eye.' },
    bye: { tr: '(Biber değirmenini havada döndürür) Ooo, çok şık!', en: '(Spins the pepper mill mid-air) Ooh, very chic!' } },
  { id: 'temel', n: { tr: 'Temel', en: 'Temel' }, me: { tr: 'Ben Temel! Herkes bana \'Uy uşağum\' der, ben de herkese uşağum derum!', en: 'I\'m Temel! Everyone calls me \'Hey laddie\', and I call everyone laddie!' }, sfx: 'whistle', fav: 'hamsi', job: { tr: 'Karadenizli fıkra kahramanı', en: 'Black Sea joke hero' },
    trait: { tr: 'Hamsisiz yapamaz; hep Dursun\'a da götürür. (Halk fıkralarının kahramanı.)', en: 'Can\'t live without anchovies; always brings some to Dursun. (A folk-joke hero.)' },
    qty: [6, 9],
    look: { coat: '#1f4e6b', coat2: '#2f6b8f', knit: '#cfe3f0', beanie: '#1a1a1a', thickMust: true, hair: '#161010', hairStyle: 0, sk: 0, pants: '#2b3a45' },
    hi: { tr: 'Uşağum, hamsi yoksa hayat da yoktur!', en: 'Lad, no anchovies, no life!' },
    bye: { tr: 'Dursun\'a da bir kasa, hadi eyvallah!', en: 'One crate for Dursun too — cheers!' } },

  /* ---------- DÜNYADAN MİSAFİRLER — liman turuna gelen renkli tipler (hepsi özgün karakterdir) ---------- */
  { id: 'gordon', n: { tr: 'Öfkeli Ömer', en: 'Fuming Omer' }, me: { tr: 'Ömer! Şef! Herkes \'Öfkeli Ömer\' der. ÖFKELİ DEĞİLİM! …Biraz.', en: 'Ömer! Chef! They call me \'Angry Ömer\'. I\'M NOT ANGRY! …A bit.' }, sfx: 'kick', fav: 'levrek', job: { tr: 'Öfkeli şef', en: 'Furious chef' },
    trait: { tr: 'Önce bağırır, sonra tadına bakar; beğenirse çok iyi öder.', en: 'Shouts first, tastes second; pays very well if impressed.' },
    fx: '!', fxc: '#ff6b5a', pat: 90, tip: 1.8,
    look: { coat: '#f4f4f0', coat2: '#ffffff', chefHat: true, apron: '#2a2a2a', thickMust: true, hair: '#3a2a1a', hairStyle: 0, sk: 1, pants: '#2a2a2a' },
    hi: { tr: 'Bu balık… BU BALIK… mükemmel. Neden bağırdım bilmiyorum.', en: 'This fish… THIS FISH… is perfect. No idea why I shouted.' },
    bye: { tr: 'Tamam. Bugün kimse mutfaktan kovulmuyor.', en: 'Fine. Nobody gets kicked out of the kitchen today.' } },
  { id: 'elvin', n: { tr: 'Pomadlı Polat', en: 'Pompadour Polat' }, me: { tr: 'Polat, bebeğim. Saçımdaki pomad benden yaşlı. Uh-huh.', en: 'Polat, baby. The pomade in my hair is older than me. Uh-huh.' }, sfx: 'guitar', fav: 'somon', job: { tr: 'Eski usul rock\'n\'roll\'cu', en: 'Old-school rock\'n\'roller' },
    trait: { tr: 'Saç jölesi hiç bitmez; kuyrukta dizlerini titreterek dans eder.', en: 'Never runs out of hair gel; dances in the queue with wobbly knees.' },
    fx: '♪', fxc: '#ffd76a', dance: true,
    look: { coat: '#2f8f8a', coat2: '#43aba5', bowtie: '#1d1d24', hair: '#161010', hairStyle: 8, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Ooo bebeğim… bir kova somon, ritimle!', en: 'Ooh baby… a bucket of salmon, with rhythm!' },
    bye: { tr: 'Ritim sende, balıkçı!', en: 'You\'ve got the rhythm, fishmonger!' } },
  { id: 'ferdi', n: { tr: 'Koro Kerem', en: 'Chorus Kerem' }, me: { tr: 'Kerem! Koro Kerem! Ben \'hoop\' derim, liman \'la\' der!', en: 'Kerem! Chorus Kerem! I say \'hoop\', the harbor says \'la\'!' }, sfx: 'eyo', fav: 'palamut', job: { tr: 'Rock operası solisti', en: 'Rock opera frontman' },
    trait: { tr: 'Kuyrukta bütün limana "Hoop-la!" dedirtir.', en: 'Gets the whole harbour shouting "Hoop-la!" from the queue.' },
    fx: '♪', fxc: '#ffe27a', dance: true, pat: 190,
    look: { coat: '#b3242a', coat2: '#d03a40', beard: true, hair: '#3a2a1a', hairStyle: 5, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Hoop-laaa! Bir palamut, lütfen!', en: 'Hoop-laaa! One bonito, please!' },
    bye: { tr: 'Bu liman bir sahne, siz de korosunuz!', en: 'This harbour\'s a stage and you\'re my choir!' } },
  { id: 'fasulye', n: { tr: 'Sessiz Suat', en: 'Silent Suat' }, me: { tr: '…Suat. *lastik ördeği gösterir* …Bu da Vak.', en: '…Suat. *points at the rubber duck* …That\'s Quack.' }, sfx: 'hmm', fav: 'hamsi', job: { tr: 'Sessiz tuhaf adam', en: 'Silent odd fellow' },
    trait: { tr: 'Neredeyse hiç konuşmaz; "Hmm!" der, cebindeki lastik ördeğe danışır.', en: 'Barely speaks; goes "Hmm!" and consults the rubber duck in his pocket.' },
    fx: '?', fxc: '#ffd76a',
    look: { coat: '#4a6a4a', coat2: '#608a60', bowtie: '#e6b93a', beanie: '#c8553d', hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#3a3226' },
    hi: { tr: 'Hmm? …Hmm!', en: 'Hmm? …Hmm!' },
    bye: { tr: '(Lastik ördeğine balığı gösterir) Vak!', en: '(Shows the fish to his rubber duck) Quack!' } },
  { id: 'serlok', n: { tr: 'Şerlok Holmez', en: 'Shirlock Holmz' }, me: { tr: 'Şerlok Holmez. Çizmenizdeki kumdan, sabah iskelede olduğunuzu biliyorum.', en: 'Şerlok Holmez. From the sand on your boots, you were on the pier this morning.' }, sfx: 'hmm', fav: 'uskumru', job: { tr: 'Dedektif', en: 'Detective' },
    trait: { tr: 'Balığa bakıp nerede, ne zaman tutulduğunu söyler. (Klasik romanlardan esinli.)', en: 'Deduces where and when a fish was caught at a glance. (Inspired by classic novels.)' },
    fx: '?', fxc: '#c9a15e',
    look: { tall: 1, coat: '#7a6a4a', coat2: '#94835e', cap: '#8a7a55', pipe: true, hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#3a3226' },
    hi: { tr: 'Basit, sevgili tezgâhtar: bu balık bu sabah 6.14\'te tutulmuş.', en: 'Elementary, dear vendor: caught this morning at 6:14.' },
    bye: { tr: 'Dava kapandı. Balık da paketlendi.', en: 'Case closed. Fish wrapped.' } },
  { id: 'sinap', n: { tr: 'Sakin Selim', en: 'Mellow Selim' }, me: { tr: 'Selim… derler… bana. Sakin… Selim. Acele… yok.', en: 'They… call me… Selim. Calm… Selim. No… rush.' }, sfx: 'drum', fav: 'somon', job: { tr: 'Rahat rapçi', en: 'Laid-back rapper' },
    trait: { tr: 'Çok yavaş ve rahat konuşur; hiç acelesi yoktur.', en: 'Talks slow and chill; never in a hurry.' },
    fx: '♪', fxc: '#8ef2a2', pat: 280,
    look: { tall: 1, coat: '#e6b93a', coat2: '#f0cf5a', cap: '#1d1d24', chain: true, hair: '#161010', hairStyle: 0, sk: 3, pants: '#1f2a36' },
    hi: { tr: 'Yooo… taze mi bu balık? Aceleye gerek yok…', en: 'Yooo… this fish fresh? No rush…' },
    bye: { tr: 'Rahatına bak, balıkçı kardeş.', en: 'Stay easy, fish bro.' } },
  { id: 'kaya', n: { tr: 'Güçlü Güven', en: 'Mighty Guven' }, me: { tr: 'Güven! Güreşte yenilmedim, kasada da yenilmem. Herkes \'Güçlü\' der!', en: 'Güven! Never lost a wrestle, never lost a crate. They call me \'Mighty\'!' }, sfx: 'drum', fav: 'ton', job: { tr: 'Güreşçi-oyuncu', en: 'Wrestler-actor' },
    trait: { tr: 'Kasayı tek eliyle taşır; kaslarını gösterip çok alır.', en: 'Carries a crate in one hand; flexes and buys a lot.' },
    qty: [8, 12],
    look: { tall: 1, coat: '#3a5a2a', coat2: '#4f783a', headband: '#c8553d', beard: true, hair: '#3a2a1a', hairStyle: 0, sk: 2, pants: '#2a2a33' },
    hi: { tr: 'Bu kasa hafif mi? Bana ikisini ver!', en: 'This crate light? Give me two!' },
    bye: { tr: 'İşte bu! Pazılar da onaylıyor.', en: 'That\'s it! The biceps approve.' } },
  { id: 'arnavut', n: { tr: 'Robotik Rüştü', en: 'Robo Rustu' }, me: { tr: 'Kimlik: Rüştü. Görev: emekli usta. Lakap: Robotik. Selamlama tamamlandı.', en: 'ID: Rüştü. Role: retired foreman. Nickname: Robotic. Greeting complete.' }, sfx: 'robot', fav: 'hamsi', job: { tr: 'Emekli fabrika ustası', en: 'Retired factory foreman' },
    trait: { tr: 'Robot gibi konuşur; her gün tam aynı saatte gelir.', en: 'Talks like a robot; shows up at exactly the same time every day.' },
    look: { tall: 1, coat: '#5a6470', coat2: '#737e8a', vest: '#e6b93a', glasses: true, hair: '#9a9a92', hairStyle: 0, sk: 0, pants: '#2e343c' },
    hi: { tr: 'Bir kasa hamsi. Hemen. İşlem başlatıldı.', en: 'One crate of anchovies. Now. Process started.' },
    bye: { tr: 'Görev tamamlandı. Yarın aynı saatte.', en: 'Task complete. Same time tomorrow.' } },
  { id: 'teylan', n: { tr: 'Şarkıcı Şirin', en: 'Songbird Shirin' }, me: { tr: 'Şirin ben! Adımı nakarata koydum, belki duymuşsundur: Şi-rin, Şi-rin!', en: 'I\'m Şirin! My name\'s in a chorus, maybe you\'ve heard it: Shi-rin, Shi-rin!' }, sfx: 'sing', fav: 'levrek', job: { tr: 'Pop prensesi', en: 'Pop princess' },
    trait: { tr: 'Her alışveriş hakkında şarkı yazar; hayranları peşinde.', en: 'Writes a song about every purchase; fans follow her everywhere.' },
    fx: '♥', fxc: '#ff8fb0',
    look: { coat: '#7a3a8a', coat2: '#9450a6', hair: '#2a1a12', hairStyle: 3, sk: 1, skirt: '#3a1a4a' },
    hi: { tr: 'Bu levrek hakkında da bir şarkı yazacağım.', en: 'I\'m writing a song about this sea bass.' },
    bye: { tr: 'Bu alışveriş de albüme girdi!', en: 'This purchase just made the album!' } },
  { id: 'opra', n: { tr: 'Cömert Cemile', en: 'Generous Cemile' }, me: { tr: 'Cemile ben, herkes \'Cömert Cemile\' der. Bugün de cömertliğim tutuyor!', en: 'I\'m Cemile, they call me \'Generous Cemile\'. Feeling generous again today!' }, sfx: 'fanfare', fav: 'somon', job: { tr: 'Talk show kraliçesi', en: 'Talk show queen' },
    trait: { tr: 'Kuyruktaki herkese balık ısmarlar!', en: 'Buys fish for everyone in the queue!' },
    qty: [10, 14], tip: 1.3, fx: '$', fxc: '#ffd76a',
    look: { belly: 1, coat: '#c8553d', coat2: '#e06a50', scarf: '#e6b93a', scarfDots: '#c8553d', hair: '#161010', hairStyle: 0, sk: 2, skirt: '#5a2a1a' },
    hi: { tr: 'Herkes dinlesin: bugün balıklar benden!', en: 'Listen up, everyone: the fish are on me today!' },
    bye: { tr: 'Hepinize bir kasa, benden olsun!', en: 'A crate for all of you — on me!' } },
  { id: 'mikail', n: { tr: 'Dansçı Deniz', en: 'Dancer Deniz' }, me: { tr: 'Deniz! Dans hocası! Bir, iki, üç… isim tamam, şimdi adım!', en: 'Deniz! Dance teacher! One, two, three… name done, now the steps!' }, sfx: 'eyo', fav: 'palamut', job: { tr: 'Dans hocası', en: 'Dance teacher' },
    trait: { tr: 'Kuyruğa geri geri kayarak gelir; her adımı sayar.', en: 'Glides into the queue backwards, counting every step.' },
    fx: '✦', fxc: '#ffffff', moon: true,
    look: { coat: '#2f6f9f', coat2: '#4388bb', beanie: '#1d1d24', hair: '#161010', hairStyle: 3, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Adım, adım, kay… bir palamut, lütfen!', en: 'Step, step, glide… one bonito, please!' },
    bye: { tr: '(Geri geri kayarak gider) Beş, altı, yedi, sekiz!', en: '(Glides away backwards) Five, six, seven, eight!' } },
  { id: 'bobros', n: { tr: 'Fırça Ferit', en: 'Brushstroke Ferit' }, me: { tr: 'Ben Ferit. Fırçamla mutlu küçük dalgalar çizerim. Hata yoktur, mutlu kazalar vardır.', en: 'I\'m Ferit. I paint happy little waves. No mistakes, only happy accidents.' }, sfx: 'chime', fav: 'uskumru', job: { tr: 'Televizyon ressamı', en: 'TV painter' },
    trait: { tr: 'Sakin mi sakin; her lekeden bir dalga, her dalgadan bir tablo çıkarır.', en: 'Serenely calm; turns every smudge into a wave, every wave into a painting.' },
    fx: '✦', fxc: '#8fd8ff', pat: 280,
    look: { coat: '#c8a24a', coat2: '#dcb860', glasses: true, beanie: '#1d1d24', hair: '#9a9a92', hairStyle: 0, sk: 1, pants: '#2e3a4a' },
    hi: { tr: 'Bir uskumru… bir de deniz mavisi. Tuval hazır.', en: 'One mackerel… and a touch of sea blue. Canvas ready.' },
    bye: { tr: 'Her lekeden bir dalga olur.', en: 'Every smudge becomes a wave.' } },
  { id: 'jami', n: { tr: 'Limoncu Levent', en: 'Lemon-squeeze Levent' }, me: { tr: 'Levent, şef! Bana \'Limoncu\' derler, cebimde hep yarım limon var!', en: 'Levent, chef! They call me \'Lemon Lad\'; there\'s always half a lemon in my pocket!' }, sfx: 'sizzle', fav: 'levrek', job: { tr: 'Genç şef', en: 'Cheeky young chef' },
    trait: { tr: 'Her şeye bir tutam zeytinyağı, bir sıkım limon; koşarak gelir.', en: 'A drizzle of olive oil and a squeeze of lemon on everything; arrives at a jog.' },
    fx: '·', fxc: '#c8e07a',
    look: { coat: '#6a8a3a', coat2: '#82a64c', apron: '#e8eef4', hair: '#5a3a22', hairStyle: 5, sk: 1, pants: '#2a3a4a' },
    hi: { tr: 'Bir tutam zeytinyağı, bir sıkım limon… şahane!', en: 'A drizzle of oil, a squeeze of lemon… gorgeous!' },
    bye: { tr: 'Şahane! Mutfakta görüşürüz!', en: 'Gorgeous! See you in the kitchen!' } },
  { id: 'atinbara', n: { tr: 'Fısıltı Fikret', en: 'Whispering Fikret' }, me: { tr: '*fısıltı* Fikret… belgeselci… Şşş, balıklar ürkmesin…', en: '*whisper* Fikret… documentary voice… Shh, don\'t startle the fish…' }, sfx: 'sigh', fav: 'uskumru', job: { tr: 'Belgesel anlatıcısı', en: 'Nature narrator' },
    trait: { tr: 'Fısıldayarak konuşur; kuyruğu vahşi yaşam belgeseli gibi anlatır.', en: 'Whispers; narrates the queue like a wildlife documentary.' },
    pat: 240,
    look: { coat: '#5a7a4a', coat2: '#6f9460', sunHat: '#c9b48a', glasses: true, hair: '#9a9a92', hairStyle: 0, sk: 1, pants: '#5a4a32' },
    hi: { tr: 'Ve işte… vahşi uskumru, doğal ortamında…', en: 'And here… the wild mackerel, in its natural habitat…' },
    bye: { tr: 'Doğa… ne muhteşem… bir torba daha.', en: 'Nature… how magnificent… one more bag.' } },
  { id: 'cak', n: { tr: 'Demir Yumruk Doğan', en: 'Iron-Fist Dogan' }, me: { tr: 'Doğan. \'Demir Yumruk\' lakabını ben koymadım, yumruğum koydu.', en: 'Doğan. I didn\'t choose \'Iron Fist\'. My fist did.' }, sfx: 'kick', fav: 'ton', job: { tr: 'Efsane dövüşçü', en: 'Legendary fighter' },
    trait: { tr: 'Balık tutmaz, balıklar ona teslim olur. Beklemeyi sevmez, parayı fazlasıyla öder.', en: 'Doesn\'t catch fish — fish surrender. Hates waiting, overpays.' },
    fx: '!', fxc: '#ffb27a', pat: 75, tip: 2.0,
    look: { coat: '#1d1d24', coat2: '#34343f', headband: '#b3242a', must: true, sash: '#1d1d24', hair: '#161010', hairStyle: 4, sk: 1, pants: '#1d1d24' },
    hi: { tr: 'Ben sıraya girmem. Sıra bana girer.', en: 'I don\'t wait in line. The line waits for me.' },
    bye: { tr: 'Bu tezgâh artık güvende.', en: 'This stall is now safe.' } },
  { id: 'gigi', n: { tr: 'Pullu Pınar', en: 'Sequin Pinar' }, me: { tr: 'Pınar, darling! Moda tasarımcısı. Bana \'Pullu Pınar\' derler, haklılar.', en: 'Pınar, darling! Fashion designer. They call me \'Scaly Pınar\'; fair enough.' }, sfx: 'camera', fav: 'uskumru', job: { tr: 'Avangart modacı', en: 'Avant-garde designer' },
    trait: { tr: 'Balık pulundan elbise diker ve giyer. Evet, gerçekten.', en: 'Sews and wears dresses made of fish scales. Yes, really.' },
    fx: '✦', fxc: '#dfe6ff', tip: 1.4,
    look: { coat: '#8fa9bd', coat2: '#b0c6d6', scales: '#5f7f96', glasses: true, hair: '#2a8a8a', hairStyle: 6, sk: 1, skirt: '#6f8fa8' },
    hi: { tr: 'Bu elbiseye bir uskumru daha lazım, darling!', en: 'This dress needs one more mackerel, darling!' },
    bye: { tr: 'Pul pul, parıl parıl! Moda harikası!', en: 'Scales and sparkles! Fashion miracle!' } },
  { id: 'edsirin', n: { tr: 'Kızıl Kenan', en: 'Ginger Kenan' }, me: { tr: 'Kenan. Saçım kızıl, gitarım akortlu. Sokaklar bana \'Kızıl\' der.', en: 'Kenan. Red hair, guitar in tune. The streets call me \'Red\'.' }, sfx: 'guitar', fav: 'palamut', job: { tr: 'Sokak şarkıcısı', en: 'Street songwriter' },
    trait: { tr: 'Gitarıyla gelir, her tezgâha bir aşk şarkısı söyler.', en: 'Shows up with his guitar and sings each stall a love song.' },
    fx: '♪', fxc: '#ffb27a',
    look: { coat: '#3a5a7a', coat2: '#4f7496', beanie: '#6a8a3a', guitar: '#b06a2a', hair: '#c2552a', hairStyle: 1, sk: 0, pants: '#2a3a4a' },
    hi: { tr: 'Gitarım hazır… bu palamuda bir şarkı yazdım.', en: 'Guitar\'s ready… I wrote this bonito a song.' },
    bye: { tr: 'Bu şarkının nakaratı sensin, palamut!', en: 'You\'re the chorus of this song, bonito!' } },

  /* ---------- KOMİK MESLEKLER ---------- */
  { id: 'mahmut', n: { tr: 'Mahmut', en: 'Mahmut the Gull Tamer' }, me: { tr: 'Mahmut ben, bu da Kaptan Martı. Ben terbiye ederim, o terbiye etmez.', en: 'I\'m Mahmut, and this is Captain Gull. I train him; he doesn\'t train back.' }, sfx: 'gull', fav: 'hamsi', job: { tr: 'Martı terbiyecisi', en: 'Seagull trainer' },
    trait: { tr: 'Omzunda martısıyla gezer; aldığının yarısı martıya.', en: 'Walks around with a gull on his shoulder; half of it goes to the bird.' },
    qty: [5, 8], fx: '~', fxc: '#ffffff',
    look: { coat: '#3a6a8a', coat2: '#5084a6', bird: '#f4f4f0', cap: '#23384a', must: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2b3a45' },
    hi: { tr: 'Kaptan Martı bugün aç, en tazesinden!', en: 'Captain Gull is hungry today — the freshest!' },
    bye: { tr: 'Martı onayladı: "Gak!"', en: 'The gull approves: "Squawk!"' } },
  { id: 'sabri', n: { tr: 'Sabri', en: 'Patient Sabri' }, me: { tr: 'Sabri. Mesleğim beklemek. Adım da zaten sabırdan geliyor.', en: 'Sabri. My job is waiting. My name literally means patience.' }, sfx: 'sigh', fav: 'uskumru', job: { tr: 'Profesyonel sıra bekleyici', en: 'Professional queue-sitter' },
    trait: { tr: 'Başkaları yerine sırada bekler; sabrı sonsuz.', en: 'Waits in line for other people; infinite patience.' },
    pat: 420,
    look: { short: 1, belly: 1, coat: '#8a7a5a', coat2: '#a4946f', sunHat: '#e8dcb8', bag: true, hair: '#6f604b', hairStyle: 4, sk: 1, pants: '#4a4232' },
    hi: { tr: 'Acele yok. Ben işimi yapıyorum: beklemek.', en: 'No rush. I\'m doing my job: waiting.' },
    bye: { tr: 'Bugün 14 sırada bekledim, rekor!', en: 'Fourteen queues today — a record!' } },
  { id: 'bedia', n: { tr: 'Bedia Abla', en: 'Sister Bedia' }, me: { tr: 'Bedia Abla derler bana. Pula bakarım, kısmet çıkar. Seninki de çıkacak.', en: 'They call me Sister Bedia. I read the scales; fortunes come out. Yours will too.' }, sfx: 'chime', fav: 'levrek', job: { tr: 'Balık pulu falcısı', en: 'Fish-scale fortune teller' },
    trait: { tr: 'Fala balık pulunda bakar; tezgâhına bereket okur.', en: 'Reads fortunes in fish scales; blesses your stall.' },
    fx: '✦', fxc: '#d0a0ff', rep: 6,
    look: { belly: 1, coat: '#5a2a6a', coat2: '#743e88', scarf: '#8a3aa8', scarfDots: '#ffd76a', chain: true, bigBag: '#3a1a4a', hair: '#161010', sk: 1, skirt: '#2a1a3a' },
    hi: { tr: 'Pulunda bir yol görüyorum… ve bir kasa levrek.', en: 'I see a journey in your scales… and a crate of sea bass.' },
    bye: { tr: 'Yolun açık, tezgâhın bereketli olsun!', en: 'Clear roads and full crates to you!' } },
  { id: 'recep', n: { tr: 'Tek Göz Recep', en: 'One-Eyed Renny' }, me: { tr: 'Tek Göz Recep! Yedi deniz gezdim, sekizincisi bu koy. Ahoy!', en: 'One-Eyed Recep! Sailed seven seas; this cove\'s the eighth. Ahoy!' }, sfx: 'parrot', fav: 'somon', job: { tr: 'Emekli korsan', en: 'Retired pirate' },
    trait: { tr: 'Göz bandı, omzunda papağan; ödemeyi altınla yapar.', en: 'Eyepatch, parrot on shoulder; pays in gold.' },
    fx: '$', fxc: '#ffd76a', tip: 1.6,
    look: { belly: 1, coat: '#8d2a2a', coat2: '#a8403a', tophat: '#1a1a1a', eyepatch: true, beard: true, bird: '#3aa84a', sash: '#d9a441', hair: '#161010', hairStyle: 2, sk: 1, pants: '#2a2018' },
    hi: { tr: 'Yo-ho-ho! Bir sandık somon, tayfa!', en: 'Yo-ho-ho! A chest of salmon, crew!' },
    bye: { tr: 'Hazine bu tezgâhta saklıymış, arrr!', en: 'So the treasure was in this stall, arrr!' } },
  { id: 'miril', n: { tr: 'Mırıl Bey', en: 'Mr. Purrington' }, me: { tr: 'Mırıl Bey, Kedi Sendikası başkanı. Kırk üyem var, kırkı da aç.', en: 'Mr. Purr, president of the Cat Union. Forty members, all forty hungry.' }, sfx: 'meow', fav: 'hamsi', job: { tr: 'Kedi sendikası başkanı', en: 'Cat union president' },
    trait: { tr: 'Limanın kedileri adına toplu alım yapar. Pazarlık yok.', en: 'Buys in bulk on behalf of the harbour cats. No haggling.' },
    qty: [9, 12], fx: '♥', fxc: '#ffd0a0',
    look: { coat: '#d08a3a', coat2: '#e8a452', vest: '#3a2f28', bowtie: '#1d1d24', glasses: true, notebook: true, hair: '#9a6a3a', hairStyle: 1, sk: 0, pants: '#3a2f28' },
    hi: { tr: 'Sendikamız adına: 40 kedi, 40 hamsi. Pazarlık yok!', en: 'On behalf of the union: 40 cats, 40 anchovies. No haggling!' },
    bye: { tr: 'Miyav. Yani… teşekkürler.', en: 'Meow. I mean… thank you.' } },
  { id: 'selin', n: { tr: 'Selfi Selin', en: 'Selfie Selin' }, me: { tr: 'Selin! Selfi Selin! Etiketle beni, olur mu? Yüz bin takipçi!', en: 'Selin! Selfie Selin! Tag me, okay? A hundred thousand followers!' }, sfx: 'camera', fav: 'somon', job: { tr: 'Fenomen', en: 'Influencer' },
    trait: { tr: 'Almadan önce otuz selfie çeker; ışığı beğenmezse bekler.', en: 'Takes thirty selfies first; waits if the light is wrong.' },
    fx: '✦', fxc: '#ffffff', pat: 180, rep: 5,
    look: { coat: '#f08ab0', coat2: '#ffa8c8', shades: true, phone: true, hair: '#e07aa8', hairStyle: 3, sk: 0, skirt: '#3a2a4a' },
    hi: { tr: 'Dur dur, önce bir selfie! Işık süper!', en: 'Wait wait, selfie first! The light is amazing!' },
    bye: { tr: 'Hikâyeye attım, sen de fenomen oldun!', en: 'Posted it — you\'re famous now!' } },
  /* ---------- v2.9: MEKANİKLİ ÖZEL MÜŞTERİLER (her birinin kendine özgü bir etkisi var; sayılar game.js › SPEC_CFG) ----------
     mech  : etki türü (forecast aura inspect review partial selfie horon credit live chain strict rush calm night souvenir records tea)
     minLv : en az itibar seviyesi · slot: 'day' yalnız gündüz, 'eve' yalnız kapanış müşterisi · rare: seçilme ağırlığı (1 normal)
     hidden: kendini belli etmez (etiket/söz yok) · only: yalnız zincirle gelir · mad: kızgın giderken söylediği */
  { id: 'nuri', n: { tr: 'Fırtına Kaptanı Nuri', en: 'Storm Captain Nuri' }, mech: 'forecast', minLv: 3, rare: 0.7, sfx: 'whistle', fav: 'uskumru',
    job: { tr: 'Emekli kaptan', en: 'Retired captain' }, pat: 220, tip: 1.5, rep: 2, fx: '~', fxc: '#bfe2f2',
    trait: { tr: 'Kırk yıl Karadeniz\'in öfkesini okumuş. Memnun giderse yarının havasını söyler; ertesi gün ağlar biraz daha hızlı dolar.', en: 'Read the Black Sea\'s temper for forty years. Leave him happy and he tells you tomorrow\'s weather; nets fill a bit faster next day.' },
    look: { tall: 1, coat: '#1f3a52', coat2: '#2e5272', cap: '#0f2030', beard: true, hair: '#d8d4cc', hairStyle: 0, sk: 1, pants: '#1a2836', pipe: true },
    me: { tr: 'Nuri derler, Fırtına Kaptanı. Kırk yıl denizin suratına baktım.', en: 'Nuri, they call me Storm Captain. Forty years I stared the sea in the face.' },
    hi: { tr: 'Deniz bugün sakin, yarına güvenme evlat. Bir uskumru ver.', en: 'Calm sea today, don\'t trust tomorrow, lad. A mackerel, please.' },
    bye: { tr: 'Eline sağlık, rüzgâr arkandan essin.', en: 'Well done, may the wind be at your back.' },
    mad: { tr: 'Bu hızla rüzgârı bile kaçırırsın.', en: 'At this pace you\'d miss the wind itself.' } },
  { id: 'reisdede', n: { tr: 'Reis Dede', en: 'Old Skipper' }, mech: 'aura', minLv: 2, rare: 0.5, sfx: 'hmm', fav: 'hamsi',
    job: { tr: 'Koyun hafızası', en: 'The cove\'s memory' }, pat: 400, tip: 1.2, rep: 2, fx: '·', fxc: '#e8dcc0',
    trait: { tr: 'Koyun yaşayan hafızası; kimse onun önünde sesini yükseltmez. Tezgâhtayken aynı kuyruktakilerin sabrı yarı hızla azalır.', en: 'The cove\'s living memory; nobody raises their voice before him. While he waits, the rest of his queue loses patience at half speed.' },
    look: { short: 1, coat: '#5a4a3a', coat2: '#6e5c48', beanie: '#3a2a20', beard: true, hair: '#eeeae0', hairStyle: 4, sk: 1, pants: '#3a3226' },
    me: { tr: 'Bana Reis Dede derler. Bu iskeleyi ben çaktım, çivisiyle.', en: 'They call me Old Skipper. I nailed this pier myself, nail by nail.' },
    hi: { tr: 'Bizim zamanımızda hamsi gümüş gibi parlardı. Bakalım seninki.', en: 'In my day anchovies shone like silver. Let\'s see yours.' },
    bye: { tr: 'İşte bu, balıkçı eli.', en: 'Now that\'s a fisherman\'s hand.' },
    mad: { tr: 'Yarın bir daha gel de ne olduğunu göster.', en: 'Come back tomorrow and show me what you\'re made of.' } },
  { id: 'mufettis', n: { tr: 'Gizli Müfettiş', en: 'Secret Inspector' }, mech: 'inspect', hidden: true, slot: 'day', minLv: 2, rare: 0.6, fav: 'hamsi',
    job: { tr: 'Belediye denetçisi', en: 'Municipal inspector' }, pat: 150, tip: 1.0, rep: 1,
    trait: { tr: 'Kimliğini kimse bilmez; sıradan bir müşteri gibi görünür. Gün sonunda raporunu bırakır: kaçan müşteri azsa ödül, çoksa ceza.', en: 'Nobody knows who they are; they look like any customer. At day\'s end they leave a report: few lost customers earns a reward, many a fine.' },
    look: { coat: '#4a5a66', coat2: '#5a6c7a', cap: '#2a3038', glasses: true, notebook: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2a3038' },
    me: { tr: '…', en: '…' }, hi: { tr: '…', en: '…' }, bye: { tr: '…', en: '…' } },
  { id: 'sedef', n: { tr: 'Gurme Sedef Hanım', en: 'Critic Sedef' }, mech: 'review', minLv: 3, rare: 0.5, sfx: 'chime', fav: 'levrek',
    job: { tr: 'Yemek eleştirmeni', en: 'Food critic' }, pat: 75, tip: 2.0, rep: 2, qty: [1, 2], fx: '✦', fxc: '#ffd76a',
    trait: { tr: 'Tek cümleyle bir tezgâhı batırıp birini kaldırır. Memnun kalırsa ertesi gün müşteri akışı artar; kızarsa azalır.', en: 'One sentence from her sinks a stall or lifts it. Please her and tomorrow brings more customers; anger her and fewer.' },
    look: { tall: 1, coat: '#2a2a3a', coat2: '#3a3a52', scarf: '#c04060', glasses: true, notebook: true, hair: '#1a1210', hairStyle: 6, sk: 0, skirt: '#1e1e2a' },
    me: { tr: 'Sedef. Yazılarımı okumuşsundur, okumadıysan yarın okursun.', en: 'Sedef. You\'ve read my columns; if not, you will tomorrow.' },
    hi: { tr: 'Tek bir levrek. Kokusundan yazı çıkacak mı, göreceğiz.', en: 'One sea bass. We\'ll see if its scent deserves a column.' },
    bye: { tr: 'Bunu yazmaya değer.', en: 'This is worth writing about.' },
    mad: { tr: 'Bu… yorumsuz kalsın.', en: 'This… shall go without comment.' } },
  { id: 'selma', n: { tr: 'Rehber Selma', en: 'Guide Selma' }, mech: 'partial', minLv: 2, rare: 0.7, sfx: 'camera', fav: 'hamsi',
    job: { tr: 'Tur rehberi (+6 turist)', en: 'Tour guide (+6 tourists)' }, pat: 200, tip: 1.6, rep: 2, qty: [12, 18], fx: '!', fxc: '#ff9a3c',
    trait: { tr: 'Arkasında altı turistle gelir, tek siparişte koca bir grup. Süre biterse eksik de olsa teslim ettiğin kadarını öder.', en: 'Arrives with six tourists, a whole group in one order. If time runs out she still pays for what you delivered.' },
    look: { coat: '#e8762b', coat2: '#f5914a', sunHat: '#f0ece0', bag: true, hair: '#3d2a1a', hairStyle: 3, sk: 1, pants: '#2f3a5a' },
    me: { tr: 'Selma ben, rehber! Arkamdaki altı kişi benimle, fotoğraf makineleri hazır!', en: 'Selma, tour guide! The six behind me are with me, cameras ready!' },
    hi: { tr: 'Arkadaşlar, bu yöre yemeği: HAMSİ! Herkese bir porsiyon!', en: 'Friends, the local dish: ANCHOVY! A portion for everyone!' },
    bye: { tr: 'Fantastik! Hepsi yedi, hepsi fotoğraf çekti.', en: 'Fantastic! Everyone ate, everyone took photos.' },
    mad: { tr: 'Otobüs bekliyor, bu kadarıyla gidiyoruz!', en: 'The bus is waiting, we\'re leaving with this much!' } },
  { id: 'fotocift', n: { tr: 'Fotoğrafçı Çift', en: 'Photographer Couple' }, mech: 'selfie', rare: 0.9, sfx: 'camera', fav: 'levrek',
    job: { tr: 'Gezgin turistler', en: 'Travelling tourists' }, pat: 210, tip: 1.6, rep: 1, fx: '✦', fxc: '#ffffff',
    trait: { tr: 'İşaret diliyle pazarlık eder ama bahşişi boldur. Tezgâhla selfie çeker: koyda ne kadar süs varsa o kadar çok öder.', en: 'They bargain in sign language but tip well. They take a selfie with the stall: the more decorations in the cove, the more they pay.' },
    look: { coat: '#4fb3e8', coat2: '#6cc6ff', sunHat: '#f4f0e6', shades: true, phone: true, hair: '#d9a441', hairStyle: 1, sk: 0, pants: '#3a4a5a' },
    me: { tr: 'Hello! We… Lena & Jo. Turist! Hamsi?', en: 'Hello! We… Lena & Jo. Tourists! Hamsi?' },
    hi: { tr: 'Hamsi? Hamsi! *fotoğraf çeker*', en: 'Hamsi? Hamsi! *snaps a photo*' },
    bye: { tr: 'Very nice, very fresh! Teşekkür!', en: 'Very nice, very fresh! Teşekkür!' },
    mad: { tr: 'Hmm… not this?', en: 'Hmm… not this?' } },
  { id: 'horon', n: { tr: 'Horon Ekibi', en: 'Horon Troupe' }, mech: 'horon', minLv: 2, rare: 0.45, sfx: 'drum', fav: 'hamsi',
    job: { tr: 'Kemençeci ve üç oyuncu', en: 'Kemenche player and three dancers' }, pat: 260, tip: 2.0, rep: 2, qty: [6, 10], fx: '♪', fxc: '#ff6b8a', dance: true,
    trait: { tr: 'Kıyıya inince yağmuru bile dans ettirirler. Gelince müzik horona döner ve 15 sn boyunca bütün kuyruklarda sabır donar.', en: 'They make even the rain dance. When they arrive the music turns to horon and for 15 s nobody in any queue loses patience.' },
    look: { coat: '#2a2a2a', coat2: '#3a3a3a', vest: '#8a1a1a', headband: '#c0282a', thickMust: true, hair: '#1d1713', hairStyle: 0, sk: 1, pants: '#1a1a1a' },
    me: { tr: 'Biz Horon Ekibiyuk! Kemençe bende, ayaklar onlarda!', en: 'We\'re the Horon Troupe! I\'ve got the kemenche, they\'ve got the feet!' },
    hi: { tr: 'Çal kemençe, çal! Dört kişiye hamsi, uşağum!', en: 'Play, kemenche, play! Anchovies for four, laddie!' },
    bye: { tr: 'Eline sağlık, bir daha gelir oynaruk!', en: 'Well done, we\'ll come back and dance!' },
    mad: { tr: 'Bu ritimle olmaz.', en: 'Can\'t dance to this rhythm.' } },
  { id: 'kazim', n: { tr: 'Muhtar Kâzım', en: 'Headman Kâzım' }, mech: 'credit', minLv: 2, rare: 0.7, sfx: 'hmm', fav: 'uskumru',
    job: { tr: 'Mahalle muhtarı', en: 'Neighbourhood headman' }, pat: 180, tip: 1.2, rep: 2, fx: '$', fxc: '#9fd3b0',
    trait: { tr: 'Koyun hem kâğıdı hem kalbi onun elinde. Veresiye alır, ertesi sabah borcunu üstüne biraz koyarak öder.', en: 'Holds both the cove\'s paperwork and its heart. Buys on credit and pays it back next morning with a little extra.' },
    look: { belly: 1, coat: '#3a3a2a', coat2: '#4a4a36', cap: '#2a2018', thickMust: true, sash: '#8a6a3a', hair: '#6a6a66', hairStyle: 4, sk: 1, pants: '#2a2018' },
    me: { tr: 'Kâzım, muhtar. Bu mahallede kim ne yer, ben bilirim.', en: 'Kâzım, the headman. I know who eats what in this neighbourhood.' },
    hi: { tr: 'Hesabı yarın kapatırız, sen bana güven.', en: 'We\'ll settle up tomorrow, you can trust me.' },
    bye: { tr: 'Mahalleye seni anlatırım.', en: 'I\'ll tell the whole neighbourhood about you.' },
    mad: { tr: 'Hmm, bunu unutmayacağım.', en: 'Hmm, I won\'t forget this.' } },
  { id: 'muhabir', n: { tr: 'Muhabir Defne', en: 'Reporter Defne' }, mech: 'live', minLv: 3, rare: 0.5, sfx: 'camera', fav: 'palamut',
    job: { tr: 'Yerel TV muhabiri (+kameraman)', en: 'Local TV reporter (+camera)' }, pat: 90, tip: 1.5, rep: 1, fx: '!', fxc: '#ff5a6a',
    trait: { tr: 'Kamera kapanınca bile gülümseyen tek insan. Gelince 30 sn canlı yayın başlar: bu sürede her satış küçük itibar, kaçan her müşteri küçük kayıp (günlük tavanlı).', en: 'The only person who smiles after the camera stops. Her arrival starts a 30 s live broadcast: each sale earns a little reputation, each lost customer costs a little (daily cap).' },
    look: { coat: '#c0282a', coat2: '#d84040', mic: true, hair: '#2e2018', hairStyle: 3, sk: 0, skirt: '#2a2a3a' },
    me: { tr: 'Defne, Koy TV! Kameraman Ozan arkamda, ışık yanıyor!', en: 'Defne, Cove TV! Ozan\'s on camera behind me, the light\'s on!' },
    hi: { tr: 'Canlı yayındayız, Hamsi Koyu\'ndan merhaba!', en: 'We\'re live, hello from Anchovy Cove!' },
    bye: { tr: 'İzleyiciler çok beğendi!', en: 'The viewers loved it!' },
    mad: { tr: 'Bunu kurguda atacağız.', en: 'We\'ll cut this in the edit.' } },
  { id: 'sevim', n: { tr: 'Düğüncü Sevim', en: 'Wedding Planner Sevim' }, mech: 'partial', minLv: 3, rare: 0.5, sfx: 'kiss', fav: 'levrek',
    job: { tr: 'Düğün organizatörü', en: 'Wedding planner' }, pat: 300, tip: 2.2, rep: 2, qty: [18, 26], fx: '♥', fxc: '#ff8ab0',
    trait: { tr: 'Her şeyin yarına yetişeceğini söyler. Dev bir düğün siparişi verir; süre dolarsa teslim ettiğin kadarını öder ama eksik için söylenir.', en: 'Swears everything will be ready by tomorrow. Places a huge wedding order; if time runs out she pays for what you delivered but grumbles about the rest.' },
    look: { coat: '#f4e9f0', coat2: '#ffffff', sash: '#ff8ab0', bigBag: '#c06080', hair: '#6a3a2a', hairStyle: 6, sk: 0, skirt: '#8a4a6a' },
    me: { tr: 'Sevim, düğün organizasyon! Yüz kişilik düğün var, canım!', en: 'Sevim, wedding planning! A hundred-guest wedding, darling!' },
    hi: { tr: 'Yüz kişilik düğün, levrek eksik olmaz!', en: 'A hundred guests, there must be sea bass!' },
    bye: { tr: 'Mükemmel, gelin bile ağlayacak!', en: 'Perfect, even the bride will cry!' },
    mad: { tr: 'Bu eksikle düğün olmaz!', en: 'Can\'t hold a wedding with this much missing!' } },
  { id: 'mert', n: { tr: 'Küçük Mert', en: 'Little Mert' }, mech: 'chain', rare: 1, sfx: 'whistle', fav: 'hamsi', chain: 'huseyin',
    job: { tr: 'Minik oltacı', en: 'Tiny angler' }, pat: 400, tip: 0.3, rep: 1, qty: [1, 1], fx: '?', fxc: '#9fe3ff',
    trait: { tr: 'Kıyıdaki en büyük hayalci. Parası azdır; onu mutlu gönderirsen ertesi gün babası Reis Hüseyin gelir.', en: 'The biggest dreamer on the shore. Has little money; send him off happy and his father, Skipper Hüseyin, comes the next day.' },
    look: { short: 1, coat: '#e8c23a', coat2: '#f5d660', beanie: '#3f6fb0', hair: '#3d2a1a', hairStyle: 0, sk: 1, pants: '#2f3a5a' },
    me: { tr: 'Ben Mert! Büyüyünce balıkçı olacağım!', en: 'I\'m Mert! I\'m going to be a fisherman when I grow up!' },
    hi: { tr: 'Abi bir tane yeter, olta hazırım.', en: 'Just one is enough, my rod\'s ready.' },
    bye: { tr: 'Büyüyünce senin gibi olacağım! Babama söyleyeceğim!', en: 'I\'ll be just like you! I\'m telling my dad!' },
    mad: { tr: 'Param az… sorun değil.', en: 'Not much money… it\'s fine.' } },
  { id: 'huseyin', n: { tr: 'Reis Hüseyin', en: 'Skipper Hüseyin' }, mech: 'chainEnd', only: true, sfx: 'eyo', fav: 'hamsi',
    job: { tr: 'Trol reisi, Mert\'in babası', en: 'Trawler skipper, Mert\'s dad' }, pat: 220, tip: 1.8, rep: 2, qty: [8, 12], fx: '♥', fxc: '#ffd76a',
    trait: { tr: 'Oğlunu mutlu edene teşekkür etmeye gelir; büyük alır, cömert öder.', en: 'Comes to thank whoever made his son happy; buys big, pays generously.' },
    look: { tall: 1, belly: 1, coat: '#2a4a6a', coat2: '#3a5a7a', beanie: '#1a2a3a', beard: true, knit: '#cfe3f0', hair: '#2a2018', hairStyle: 0, sk: 1, pants: '#1a2836' },
    me: { tr: 'Ben Hüseyin, Mert\'in babası. Oğlan dün seni anlata anlata bitiremedi.', en: 'I\'m Hüseyin, Mert\'s father. The boy couldn\'t stop talking about you.' },
    hi: { tr: 'Teknenin ambarına göre ver, çekinme.', en: 'Fill it up for the boat\'s hold, don\'t hold back.' },
    bye: { tr: 'Oğluma iyi davrandın, unutmam.', en: 'You were good to my boy, I won\'t forget.' } },
  { id: 'hesapci', n: { tr: 'Bay Hesapçı', en: 'Mr. Tally' }, mech: 'strict', minLv: 2, rare: 0.7, sfx: 'cash', fav: 'levrek',
    job: { tr: 'Emekli muhasebeci', en: 'Retired accountant' }, pat: 85, tip: 1.0, rep: 1, fx: '$', fxc: '#ffe27a',
    trait: { tr: 'Zengin ama cimri; tartıyı gözüyle kontrol eder. Çabuk ve dürüst servise iki kat öder, beklerse şikâyet eder (küçük itibar kaybı).', en: 'Rich but stingy; checks the scale with his own eyes. Pays double for quick, honest service; complains if kept waiting (small reputation loss).' },
    look: { coat: '#3a3a3a', coat2: '#4a4a4a', vest: '#2a2a2a', tie: '#8a1a1a', glasses: true, must: true, hair: '#8a8a86', hairStyle: 4, sk: 0, pants: '#2a2a2a' },
    me: { tr: 'Hesapçı derler bana. Kırk yıl defter tuttum, bir kuruş kaçmadı.', en: 'They call me Mr. Tally. Forty years of ledgers, not a penny missed.' },
    hi: { tr: 'Bir gram eksik tartarsan anlarım.', en: 'If you weigh one gram short, I\'ll know.' },
    bye: { tr: 'İşte dürüstlük böyle olur.', en: 'Now that\'s honesty.' },
    mad: { tr: 'Seni esnaf odasına şikâyet ederim!', en: 'I\'m reporting you to the traders\' guild!' } },
  { id: 'aylin', n: { tr: 'Nöbetçi Dr. Aylin', en: 'On-call Dr. Aylin' }, mech: 'rush', minLv: 2, rare: 0.7, sfx: 'bell', fav: 'hamsi',
    job: { tr: 'Nöbetçi doktor', en: 'On-call doctor' }, pat: 50, tip: 1.0, rep: 1, qty: [1, 3], fx: '!', fxc: '#ff5a6a',
    trait: { tr: 'Bir elinde telefon, bir elinde poşet. 25 saniye içinde servis edersen üç kat öder.', en: 'Phone in one hand, bag in the other. Serve her within 25 seconds and she pays triple.' },
    look: { coat: '#eef1f4', coat2: '#ffffff', glasses: true, phone: true, hair: '#2e2018', hairStyle: 3, sk: 1, pants: '#3a4450' },
    me: { tr: 'Aylin, nöbetçi doktor. İsmimi söyledim, vakit kalmadı!', en: 'Aylin, on-call doctor. That\'s my name, now no time left!' },
    hi: { tr: 'Beş dakikam var, hızlı lütfen!', en: 'I\'ve got five minutes, quickly please!' },
    bye: { tr: 'Yetiştirdin beni, sağ ol!', en: 'You got me there in time, thanks!' },
    mad: { tr: 'Bu hızla hasta ölür!', en: 'At this speed the patient dies!' } },
  { id: 'cevdet', n: { tr: 'Cevdet Hoca', en: 'Mr. Cevdet' }, mech: 'calm', rare: 0.8, sfx: 'sing', fav: 'hamsi',
    job: { tr: 'Emekli edebiyat öğretmeni', en: 'Retired literature teacher' }, pat: 260, tip: 1.6, rep: 2, fx: '~', fxc: '#c8b0ff',
    trait: { tr: 'Siparişini şiirle verir. O kuyruktayken herkes susup dinler: aynı kuyruktakilerin sabrı daha yavaş azalır.', en: 'Orders in verse. While he\'s in line everyone hushes to listen: his queue loses patience more slowly.' },
    look: { coat: '#6a5a4a', coat2: '#7e6c5a', vest: '#4a3a2a', bowtie: '#8a1a1a', glasses: true, notebook: true, hair: '#cfcac0', hairStyle: 1, sk: 0, pants: '#3a3226' },
    me: { tr: 'Cevdet, emekli edebiyat öğretmeni. Kırk yıl Fuzuli okuttum.', en: 'Cevdet, retired literature teacher. Forty years of teaching the classics.' },
    hi: { tr: 'Denizin gümüşü, sofranın şairi… bir hamsi lütfen.', en: 'Silver of the sea, poet of the table… one anchovy, please.' },
    bye: { tr: 'Aferin, yarım sayfa şiir hak ettin.', en: 'Bravo, you\'ve earned half a page of verse.' },
    mad: { tr: 'Bu da neyin nesi?', en: 'What on earth is this?' } },
  { id: 'taksi', n: { tr: 'Gece Taksicileri', en: 'Night Cabbies' }, mech: 'night', slot: 'eve', rare: 1, sfx: 'cash', fav: 'hamsi',
    job: { tr: 'Üç vardiyalı taksici', en: 'Three late-shift cabbies' }, pat: 140, tip: 1.3, rep: 1, qty: [5, 8], fx: '!', fxc: '#ffd23a',
    trait: { tr: 'Şehrin uyumayan yarısı. Yalnız kapanışa doğru gelir; kapanış saatinde servis edilirse buçuk kat öder.', en: 'The half of town that never sleeps. Only comes near closing; served during closing time they pay one and a half times.' },
    look: { coat: '#f0c020', coat2: '#ffd23a', cap: '#2a2a2a', must: true, hair: '#2a2018', hairStyle: 0, sk: 2, pants: '#2a2a2a' },
    me: { tr: 'Biz gece taksicileriyiz, ben Turgut. Öbürleri arabada uyuyor.', en: 'We\'re the night cabbies, I\'m Turgut. The others are asleep in the car.' },
    hi: { tr: 'Vardiya sonu, üç hamsi ekmek!', en: 'End of shift, three anchovy sandwiches!' },
    bye: { tr: 'Taksimetre durdu, hesap tamam.', en: 'Meter\'s stopped, all square.' },
    mad: { tr: 'Müşteri bekliyor, çabuk!', en: 'A fare is waiting, hurry!' } },
  { id: 'gurbetci', n: { tr: 'Gurbetçi Mehmet Amca', en: 'Uncle Mehmet from Abroad' }, mech: 'souvenir', minLv: 3, rare: 0.4, sfx: 'eyo', fav: 'hamsi',
    job: { tr: 'Yurt dışından izinli', en: 'Home on holiday from abroad' }, pat: 230, tip: 2.5, rep: 2, qty: [4, 7], fx: '♥', fxc: '#ffd76a',
    trait: { tr: 'Her yıl koyun kokusunu bavulunda taşır. Memnun giderse bagajından koya bir hatıra (süs) bırakır.', en: 'Carries the cove\'s scent in his suitcase every year. Leave him happy and he leaves a keepsake (a decoration) from his trunk.' },
    look: { belly: 1, coat: '#6a7a8a', coat2: '#7e8e9e', glasses: true, must: true, bigBag: '#4a3a2a', hair: '#8a8a86', hairStyle: 4, sk: 1, pants: '#3a4450' },
    me: { tr: 'Mehmet ben, otuz yıldır gurbetteyim. Her yaz buraya dönerim.', en: 'I\'m Mehmet, thirty years abroad. Every summer I come back here.' },
    hi: { tr: 'Almanya\'da bile böyle hamsi bulamadım. Annemin yaptığı gibi olsun.', en: 'Couldn\'t find anchovies like this even in Germany. Like my mother made.' },
    bye: { tr: 'Bunu götürsem annem bile gelir! Al, bu senin.', en: 'Mother herself would come for this! Here, this is for you.' },
    mad: { tr: 'Eh… annemin ki başkaydı.', en: 'Eh… my mother\'s was different.' } },
  { id: 'hayri', n: { tr: 'Plakçı Hayri Usta', en: 'Record Collector Hayri' }, mech: 'records', rare: 0.8, sfx: 'guitar', fav: 'uskumru',
    job: { tr: 'Plak koleksiyoncusu', en: 'Record collector' }, pat: 200, tip: 1.3, rep: 1, fx: '♪', fxc: '#c8b0ff',
    trait: { tr: 'Her dükkâna girince önce hoparlörü yoklar. Çalan müziği beğenirse fazla öder; rock çalıyorsa sabrı çabuk tükenir.', en: 'Checks the speakers first in every shop. If he likes the music he pays more; if rock is playing his patience runs out fast.' },
    look: { coat: '#4a3a5a', coat2: '#5e4c70', vest: '#2a2030', glasses: true, bigBag: '#2a2a2a', hair: '#cfcac0', hairStyle: 1, sk: 0, pants: '#2a2030' },
    me: { tr: 'Hayri Usta. Plak dükkânım var, dört bin plak.', en: 'Master Hayri. I run a record shop, four thousand records.' },
    hi: { tr: 'Bu parçanın ilk baskısı bende var.', en: 'I own the first pressing of this track.' },
    hi2: { tr: 'İşte müzik buna denir! Bir uskumru, keyifle.', en: 'Now that\'s music! A mackerel, with pleasure.' },
    hi3: { tr: 'Radyoyu değiştir, kulaklarım kanıyor! Çabuk ver de gideyim.', en: 'Change the station, my ears are bleeding! Quick, let me go.' },
    bye: { tr: 'Müzik de balık da yerinde.', en: 'Music and fish, both spot on.' },
    mad: { tr: 'Bu gürültüde beklenmez.', en: 'Can\'t wait in this racket.' } },
  { id: 'cayci', n: { tr: 'Çaycı Ali', en: 'Tea Boy Ali' }, mech: 'tea', rare: 1, sfx: 'bell', fav: 'hamsi',
    job: { tr: 'Çay ocağı çırağı', en: 'Tea-house apprentice' }, pat: 400, tip: 0.5, rep: 1, qty: [1, 1], fx: '~', fxc: '#e8a060',
    trait: { tr: 'Koyun her şeyini bilir, tepsisini hiç düşürmez. Bölgeye çay dağıtır: o bekledikçe bölgedeki bütün kuyrukların sabrı daha yavaş azalır.', en: 'Knows everything in the cove and never drops his tray. Hands out tea in his zone: while he waits, every queue there loses patience more slowly.' },
    look: { short: 1, coat: '#f4f0e6', coat2: '#ffffff', vest: '#8a1a1a', hair: '#1d1713', hairStyle: 0, sk: 1, pants: '#2a2a2a', apron: '#e8dcc0' },
    me: { tr: 'Ali ben, çay ocağındanım! Herkes beni tanır.', en: 'I\'m Ali, from the tea house! Everybody knows me.' },
    hi: { tr: 'Çay geldi, çay! Abi bana da bir hamsi ekmek.', en: 'Tea\'s here, tea! And an anchovy sandwich for me.' },
    bye: { tr: 'Tepsi boş, gönül dolu!', en: 'Tray\'s empty, heart\'s full!' },
    mad: { tr: 'Tepsi düştü, yandım!', en: 'Dropped the tray, I\'m done for!' } }
];
