/* =====================================================================
   BALIKÇI TYCOON — ÖZEL İSİMLİ MÜŞTERİLER  (bu dosyayı serbestçe düzenle)
   ---------------------------------------------------------------------
   Her gün havuzdan 2 kişi gelir (dün gelenler ertesi gün tekrar gelmez).
   Yeni kişi eklemek = listeye yeni bir { ... } bloğu eklemek. Silmek = bloğu silmek.
   Ünlü parodilerinin isimleri bilerek değiştirilmiştir; gerçek kişiler değildir.

   ZORUNLU ALANLAR
     id    : benzersiz kısa kimlik (küçük harf, boşluksuz)   örn. 'temel'
     n     : ekranda görünen isim                             örn. 'Temel'
     job   : meslek          { tr: '...', en: '...' }  (ya da tek dilde 'metin')
     hi    : kuyruğa girince söylediği   { tr, en }
     bye   : mutlu ayrılırken söylediği  { tr, en }

   İSTEĞE BAĞLI — KARAKTER
     trait : huyu / özelliği (menü › ALBÜM'de görünür)   { tr, en }
     fav   : sevdiği balık: hamsi | uskumru | palamut | levrek | somon | ton
             (o tezgâh açıksa oraya gider, değilse açık herhangi bir tezgâha)

   İSTEĞE BAĞLI — OYUN ETKİSİ (yazılmazsa varsayılan)
     qty   : sipariş adedi [en az, en çok]          varsayılan [3, 5]
     pat   : sabır (saniye)                          varsayılan 150
     tip   : ödeme çarpanı (1 = normal fiyat)        varsayılan 1.1
     rep   : verdiği itibar                          varsayılan 3
     fx    : başının üstünden uçuşan işaret: '♪' '♥' '✦' '!' '?' '$' '~' '·'
     fxc   : işaretin rengi                          örn. '#ff6b8a'
     moon  : true → geri geri kayarak yürür (moonwalk)
     dance : true → kuyrukta hoplayıp dans eder

   GÖRÜNÜŞ — look: { ... }   (renkler '#rrggbb')
     sk        : ten 0 açık … 3 koyu
     hair      : saç rengi          hairStyle: 0 kısa, 1 dalgalı, 2 uzun, 3 at kuyruğu,
                                               4 kel, 5 kıvırcık/afro, 6 topuz, 7 mohikan, 8 kabarık perçem
     coat/coat2: üst giysi + omuz ışığı     pants: pantolon     skirt: uzun etek (pantolon yerine)
     tall / short / belly : 1 → uzun boy / kısa boy / göbekli
     Başlık (biri): cap, beanie, sunHat, tophat, turban (renk)  ·  fez, chefHat (true)  ·  scarf (başörtüsü, renk) + scarfDots
     Yüz: must, thickMust, beard (true) · glasses, shades (güneş gözlüğü), eyepatch, pipe (true)
     Üst: apron, vest, sash, tie, bowtie, cape (pelerin), scales (balık pulu desenli elbise), knit, headband (renk)
          chain (altın kolye, true)
     Eşya: bag, notebook, mic, phone (true) · bigBag, guitar, bird (omuzda kuş) (renk)
   ===================================================================== */
window.BT_SPECIALS = [

  /* ---------- İLK 10: mahallenin tanıdık yüzleri ---------- */
  { id: 'caner', n: 'Caner', fav: 'hamsi', job: { tr: 'Kaliteci', en: 'Quality inspector' },
    trait: { tr: 'Her balığı tek tek inceler; kedilere mutlaka pay ayırır.', en: 'Inspects every fish; always saves a share for the cats.' },
    look: { tall: 1, belly: 1, coat: '#5b6d7c', coat2: '#6f8394', hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#33393f' },
    hi: { tr: 'Önce bir bakayım… tamam, bundan alalım.', en: 'Let me take a look… right, I\'ll have this.' },
    bye: { tr: 'Kalitesi yerinde. Kedilere de bir parça ayırdım.', en: 'Quality checks out. Saved a bite for the cats.' } },
  { id: 'pelin', n: 'Pelin', fav: 'levrek', job: { tr: 'Biyolog', en: 'Biologist' },
    trait: { tr: 'Solungaca bakıp tazeliği saniyede söyler.', en: 'Reads freshness from the gills in a second.' },
    look: { coat: '#3f7f7a', coat2: '#56988f', hair: '#d9772b', hairStyle: 5, sk: 0, pants: '#2b3a45' },
    hi: { tr: 'Gözleri parlak, solungaçlar kırmızı. Güzel.', en: 'Bright eyes, red gills. Good.' },
    bye: { tr: 'Net ve temiz. Teşekkürler.', en: 'Clean and precise. Thank you.' } },
  { id: 'riza', n: 'Rıza', fav: 'hamsi', job: { tr: 'Tesisat ustası', en: 'Plumber' },
    trait: { tr: 'Sabahın köründe gelir, işe balıkla başlar.', en: 'Shows up at dawn; the day starts with fish.' },
    look: { belly: 1, coat: '#3f5f8f', coat2: '#557aa8', cap: '#2b2b2b', thickMust: true, hair: '#1d1713', hairStyle: 0, sk: 2, pants: '#2e3a4a' },
    hi: { tr: 'Sabahın köründe iş başı, önce balık!', en: 'Up at dawn — fish comes first!' },
    bye: { tr: 'Eline sağlık. Musluk bozulursa bana haber ver.', en: 'Cheers. If a tap leaks, you know who to call.' } },
  { id: 'nermin', n: 'Nermin', fav: 'uskumru', job: { tr: 'Emekli öğretmen', en: 'Retired teacher' },
    trait: { tr: 'Tezgâha not verir; düzenliysen bahşişi artar.', en: 'Grades your stall; tidy stalls get a better tip.' },
    tip: 1.25,
    look: { short: 1, belly: 1, coat: '#8a4a6a', coat2: '#a45f82', hair: '#9a9a96', hairStyle: 1, sk: 0, skirt: '#4a3a4a', bigBag: '#6b2f3a' },
    hi: { tr: 'Evladım, bugün hangisi taze?', en: 'Dear, which one is fresh today?' },
    bye: { tr: 'Aferin sana. Hep böyle düzenli ol.', en: 'Well done, dear. Keep it this tidy.' } },
  { id: 'kemal', n: 'Kemal', fav: 'levrek', job: { tr: 'Lokanta işletmecisi', en: 'Restaurant owner' },
    trait: { tr: 'Akşam servisi için toplu alır.', en: 'Buys in bulk for the evening service.' },
    qty: [5, 8],
    look: { tall: 1, coat: '#e8e2d2', coat2: '#f4efe4', vest: '#3a2f28', notebook: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2a2724' },
    hi: { tr: 'Akşam servisi için not alıyorum…', en: 'Taking notes for tonight\'s service…' },
    bye: { tr: 'Yarın yine gelirim, masalar dolu.', en: 'Back tomorrow — the tables are full.' } },
  { id: 'sule', n: 'Şule', fav: 'uskumru', job: { tr: 'Terzi', en: 'Tailor' },
    trait: { tr: 'Paketin dikişine bile bakar.', en: 'Even checks the seams on the wrapping.' },
    look: { coat: '#7a2b4a', coat2: '#94405f', hair: '#3d2a1a', hairStyle: 6, sk: 0, skirt: '#2f3a5a' },
    hi: { tr: 'Tezgâhın ne kadar derli toplu, beğendim.', en: 'Such a neat stall. I like it.' },
    bye: { tr: 'Paketi de özenli yapmışsın, sağ ol.', en: 'Wrapped with care, too. Thank you.' } },
  { id: 'okan', n: 'Okan', fav: 'hamsi', job: { tr: 'Kurye', en: 'Courier' },
    trait: { tr: 'Hep acelesi var; çabuk servis ister.', en: 'Always in a hurry; wants it fast.' },
    pat: 95,
    look: { coat: '#e0a030', coat2: '#f0bd55', bag: true, hair: '#1d1713', hairStyle: 0, sk: 2, pants: '#2b3a45' },
    hi: { tr: 'Çabuk olursak iyi olur, teslimat bekliyor!', en: 'Quick if we can — a delivery\'s waiting!' },
    bye: { tr: 'Hızlı servis, tam benlik!', en: 'Fast service, just my style!' } },
  { id: 'fatos', n: 'Fatoş', fav: 'uskumru', job: { tr: 'Ev aşçısı', en: 'Home cook' },
    trait: { tr: 'Buğulama ustası; herkese bir tabak ayırır.', en: 'Steamed-fish expert; saves everyone a plate.' },
    look: { belly: 1, coat: '#c8553d', coat2: '#dc6d55', scarf: '#e0679e', scarfDots: '#ffd76a', apron: '#f0ece0', hair: '#3d2a1a', sk: 1, skirt: '#5a3f7a' },
    hi: { tr: 'Bu akşam buğulama yapacağım, en tazesinden!', en: 'Steamed fish tonight — the freshest, please!' },
    bye: { tr: 'Afiyetle yiyelim, sana da bir tabak ayırırım!', en: 'Enjoy! I\'ll save you a plate!' } },
  { id: 'burak', n: 'Burak', fav: 'levrek', job: { tr: 'Bankacı', en: 'Banker' },
    trait: { tr: 'Kuruşu kuruşuna öder, fazlasını değil.', en: 'Pays to the penny, not a penny more.' },
    tip: 1.0,
    look: { coat: '#2f3f5a', coat2: '#43557a', vest: '#e8e2d2', beard: true, tie: '#8d2a2a', hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#252c38' },
    hi: { tr: 'Hesap kitap tamam, şimdi balık zamanı.', en: 'Books are balanced — fish time.' },
    bye: { tr: 'Teşekkürler, iyi işler.', en: 'Thanks. Good business to you.' } },
  { id: 'ayfer', n: 'Ayfer', fav: 'hamsi', job: { tr: 'Eczacı', en: 'Pharmacist' },
    trait: { tr: 'Balığı reçete gibi yazar: haftada iki kez.', en: 'Prescribes fish: twice a week.' },
    look: { coat: '#f0ece0', coat2: '#fbf8f0', glasses: true, hair: '#3d2a1a', hairStyle: 1, sk: 0, pants: '#3a4450' },
    hi: { tr: 'Omega-3 için haftada iki kez balık, reçetem bu.', en: 'Fish twice a week — that\'s my prescription.' },
    bye: { tr: 'Düzenli beslenmek önemli. Görüşürüz.', en: 'Eat regularly. See you soon.' } },

  /* ---------- YERLİ ÜNLÜ PARODİLERİ (isimler değiştirildi) ---------- */
  { id: 'tarkut', n: 'Tarkut', fav: 'levrek', job: { tr: 'Pop Megastarı', en: 'Pop megastar' },
    trait: { tr: 'Öpücük atmadan balık almaz; kuyrukta kalça sallar.', en: 'Won\'t buy without blowing a kiss; dances in the queue.' },
    fx: '♥', fxc: '#ff6b8a', dance: true, tip: 1.4,
    look: { coat: '#1d1d24', coat2: '#34343f', shades: true, chain: true, hair: '#161010', hairStyle: 1, sk: 1, pants: '#1a1a20' },
    hi: { tr: 'Şıkıdım şıkıdım… bir levrek, lütfen! Muck!', en: 'Shake it, shake it… one sea bass, please! Mwah!' },
    bye: { tr: 'Muck! Öpüldün, tezgâh!', en: 'Mwah! You\'ve been kissed, stall!' } },
  { id: 'cemal', n: 'Cemal Gırgır', fav: 'palamut', job: { tr: 'Stand-up komedyeni', en: 'Stand-up comedian' },
    trait: { tr: 'Kuyrukta şov yapar; herkes güldüğü için kimse sabırsızlanmaz.', en: 'Does a set in the queue; everyone laughs, so nobody gets impatient.' },
    fx: '!', fxc: '#ffd76a', pat: 230,
    look: { coat: '#232a33', coat2: '#39434f', must: true, hair: '#1d1713', hairStyle: 0, sk: 1, pants: '#1f252c' },
    hi: { tr: 'Şimdi… balıkçıya gittim, dedim ki abi…', en: 'So… I go to the fishmonger and I say…' },
    bye: { tr: 'Çok iyi seyircisiniz, iyi akşamlar!', en: 'You\'ve been a great crowd, good night!' } },
  { id: 'sukru', n: 'Saf Şükrü', fav: 'hamsi', job: { tr: 'Mahalle bekçisi', en: 'Night watchman' },
    trait: { tr: 'Saf ama altın kalpli; siparişini iki kez sorar, bahşişi bol.', en: 'Naive with a heart of gold; asks twice, tips big.' },
    tip: 1.5,
    look: { short: 1, coat: '#6b5a3a', coat2: '#85714c', vest: '#3a2f22', cap: '#c9a15e', must: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#3a3226' },
    hi: { tr: 'Ben bi\' şey demedim… balık dedi ki beni al!', en: 'I didn\'t say a thing… the fish said "take me"!' },
    bye: { tr: 'Hıh! Çok şükür, doyduk.', en: 'Heh! Thank goodness, we\'re fed.' } },
  { id: 'barlas', n: 'Barlas Mançı', fav: 'uskumru', job: { tr: 'Rock ozanı', en: 'Rock bard' },
    trait: { tr: 'Yüzüklerini şıngırdatır, tezgâha nasihat verir.', en: 'Jingles his rings and gives the stall life advice.' },
    fx: '♪', fxc: '#c9a0ff',
    look: { coat: '#4a2a5e', coat2: '#63407a', thickMust: true, chain: true, hair: '#1d1713', hairStyle: 2, sk: 1, pants: '#231a2c' },
    hi: { tr: 'Adam olacak tezgâh balığından belli olur!', en: 'You can tell a great stall by its fish!' },
    bye: { tr: 'Dönence… yine gelirim, hamsiye dönence!', en: 'What goes around… I\'ll come around again!' } },
  { id: 'ibo', n: 'İbo Tatlıdil', fav: 'uskumru', job: { tr: 'Türkü sanatçısı', en: 'Folk singer' },
    trait: { tr: 'Mikrofonunu hiç bırakmaz; kuyrukta uzun hava okur.', en: 'Never lets go of his mic; sings long ballads in line.' },
    fx: '♪', fxc: '#ffd76a', pat: 190,
    look: { belly: 1, coat: '#5a2a22', coat2: '#743a30', thickMust: true, mic: true, hair: '#161010', hairStyle: 5, sk: 2, pants: '#2a1c18' },
    hi: { tr: 'Haydi söyle… balık nerde, balık?', en: 'Come on, sing along… where\'s the fish?' },
    bye: { tr: 'Mis gibi! Bu türkü de senin için!', en: 'Beautiful! This next song\'s for you!' } },
  { id: 'ayda', n: 'Ayda Pekkaya', fav: 'somon', job: { tr: 'Diva', en: 'Diva' },
    trait: { tr: 'Yavaş yürür, gözlüğünü çıkarmaz, sabrı kısa ama cömert.', en: 'Walks slowly, never removes her shades; short-tempered but generous.' },
    fx: '✦', fxc: '#ffd76a', pat: 110, tip: 1.7,
    look: { coat: '#b3243a', coat2: '#cf3b52', cape: '#e8d6a0', shades: true, hair: '#ecc86a', hairStyle: 5, sk: 0, skirt: '#7a1626' },
    hi: { tr: 'Bana bu sabah tutulmuşunu verin, tatlım.', en: 'Give me this morning\'s catch, darling.' },
    bye: { tr: 'Mükemmel… size bir şarkı borçluyum!', en: 'Perfect… I owe you a song!' } },
  { id: 'adnan', n: 'Adnan Ilıcak', fav: 'palamut', job: { tr: 'TV yapımcısı', en: 'TV producer' },
    trait: { tr: 'Her şeyi yarışmaya çevirir; kameralar için toplu sipariş verir.', en: 'Turns everything into a game show; bulk-orders for the cameras.' },
    qty: [6, 9], fx: '$', fxc: '#8ef2a2',
    look: { belly: 1, coat: '#1f3550', coat2: '#2f4d72', phone: true, hair: '#3a2f28', hairStyle: 4, sk: 1, pants: '#1a2433' },
    hi: { tr: 'Bu tezgâhı prime time\'a alıyorum! "Hayatta Kalan: Balık Adası"!', en: 'This stall goes prime time! "Survivor: Fish Island"!' },
    bye: { tr: 'Reytingler tavan, kardeşim!', en: 'Ratings through the roof, brother!' } },
  { id: 'hoca', n: 'Nasır Hoca', fav: 'hamsi', job: { tr: 'Göl mayalayıcı', en: 'Lake-yogurt maker' },
    trait: { tr: 'Göle maya çalmaya gider; ters mantıklı ama hep haklı çıkar.', en: 'Tries to turn a lake into yogurt; backwards logic, always right.' },
    fx: '?', fxc: '#f0ece0', pat: 200,
    look: { belly: 1, coat: '#3f6a3a', coat2: '#56884f', turban: '#f0ece0', beard: true, sash: '#c9a15e', hair: '#d8d8d0', hairStyle: 0, sk: 1, pants: '#2e3d28' },
    hi: { tr: 'Göle maya çaldım… ya tutarsa? Tutmadı, balık alayım.', en: 'I put yogurt in the lake… what if it works? It didn\'t. Fish, then.' },
    bye: { tr: 'Ye kürküm ye… pardon, ye balığım ye!', en: 'Eat, my coat, eat… sorry, eat, my fish!' } },
  { id: 'fahri', n: 'Fahri Tezim', fav: 'levrek', job: { tr: 'Teknik direktör', en: 'Football manager' },
    trait: { tr: 'Tezgâhı taktik tahtasına çevirir; sabırsız ama imparator gibi bahşiş verir.', en: 'Treats your stall like a tactics board; impatient, tips like an emperor.' },
    fx: '!', fxc: '#ff9b8a', pat: 90, tip: 1.6,
    look: { coat: '#20242c', coat2: '#343a46', tie: '#b3242a', hair: '#e0e0da', hairStyle: 1, sk: 0, pants: '#1c1f26' },
    hi: { tr: 'Bu balığı bir de benim sistemimde görün!', en: 'Watch this fish in MY system!' },
    bye: { tr: 'Kazandık! Mağlubiyet yok, sadece hamsi var!', en: 'We won! No defeat, only anchovies!' } },
  { id: 'muslum', n: 'Müslüm Dertli', fav: 'uskumru', job: { tr: 'Arabesk sanatçısı', en: 'Arabesque singer' },
    trait: { tr: 'Her balıkta bir dert bulur; ağlarken bile alışverişini yapar.', en: 'Finds sorrow in every fish; shops even while crying.' },
    fx: '~', fxc: '#8fc0ff',
    look: { coat: '#2a2a30', coat2: '#3e3e48', glasses: true, must: true, hair: '#161010', hairStyle: 1, sk: 1, pants: '#1c1c22' },
    hi: { tr: 'Sevda yüklü kasalar… bir uskumru, bir de gözyaşı.', en: 'Crates full of heartache… one mackerel, one tear.' },
    bye: { tr: 'Hayat bu… bazen hamsi, bazen hüzün.', en: 'That\'s life… sometimes fish, sometimes sorrow.' } },
  { id: 'nazik', n: 'Nazik Mürsel', fav: 'levrek', job: { tr: 'Sanat güneşi', en: 'Sun of the stage' },
    trait: { tr: 'Aşırı kibar; "efendim" demeden cümle kurmaz. Pelerini ışıl ışıl.', en: 'Impossibly polite; every sentence ends in "sir". Sparkly cape.' },
    fx: '✦', fxc: '#dfe6ff', tip: 1.4,
    look: { coat: '#d0d6ea', coat2: '#eef1fa', cape: '#8a9ad6', bowtie: '#1d1d24', hair: '#c9c2a8', hairStyle: 8, sk: 0, pants: '#dfe3ee' },
    hi: { tr: 'Muhterem efendim, bu nadide levrekten lütfeder misiniz?', en: 'Most esteemed sir, might I have this exquisite sea bass?' },
    bye: { tr: 'Hürmetlerimle efendim. Sahnemde görüşmek üzere.', en: 'My deepest respects, sir. See you at my show.' } },
  { id: 'cuneyt', n: 'Çüneyt Kırkın', fav: 'palamut', job: { tr: 'Aksiyon yıldızı', en: 'Action star' },
    trait: { tr: 'Kasaları uçan tekmeyle taşır; hızlı iş ister.', en: 'Moves crates with flying kicks; wants it quick.' },
    fx: '!', fxc: '#ffb27a', pat: 100, dance: true,
    look: { tall: 1, coat: '#6a4028', coat2: '#8a5838', headband: '#c0282a', hair: '#161010', hairStyle: 0, sk: 1, pants: '#2a2018' },
    hi: { tr: 'Hiyaaa! Bir kasa palamut, tek hamlede!', en: 'Hi-yaaa! One crate of bonito, in one move!' },
    bye: { tr: 'Dünyayı kurtardım, şimdi de akşam yemeğini!', en: 'Saved the world — now dinner!' } },
  { id: 'hulya', n: 'Hülya Avcı', fav: 'somon', job: { tr: 'Talk show sunucusu', en: 'Talk show host' },
    trait: { tr: 'Herkese iltifat eder, sohbeti bitmez; sabrı uzun.', en: 'Compliments everyone, never stops chatting; very patient.' },
    fx: '♥', fxc: '#ffb0c8', pat: 220,
    look: { coat: '#d23f5a', coat2: '#e85c75', shades: true, hair: '#f0cf7a', hairStyle: 2, sk: 0, skirt: '#2a1a2a' },
    hi: { tr: 'Ay bu tezgâh ne güzel olmuş, canım benim!', en: 'Oh my, what a gorgeous stall, sweetie!' },
    bye: { tr: 'Öpüyorum hepinizi, bir sonraki programda görüşürüz!', en: 'Kisses to all of you, see you next show!' } },
  { id: 'haluk', n: 'Haluk Lüvent', fav: 'hamsi', job: { tr: 'Yardımsever rockçı', en: 'Charity rocker' },
    trait: { tr: 'Fazlasını ihtiyaç sahiplerine dağıtır; çok büyük alır.', en: 'Gives the extra to people in need; buys big.' },
    qty: [7, 10], fx: '♥', fxc: '#8ef2a2',
    look: { coat: '#2a2a2a', coat2: '#404040', headband: '#1d1d24', beard: true, guitar: '#8a4a22', hair: '#3a2a1a', hairStyle: 2, sk: 1, pants: '#1f2a36' },
    hi: { tr: 'Fazla ne varsa verin, mahallede dağıtacağız!', en: 'Give me all the extra — we\'ll hand it out in the neighbourhood!' },
    bye: { tr: 'İyilik bulaşıcıdır, sen de bulaş!', en: 'Kindness is contagious — catch it!' } },
  { id: 'berk', n: 'ÇZN Berk', fav: 'ton', job: { tr: 'Sosyal medya aşçısı', en: 'Viral food creator' },
    trait: { tr: 'Hep kameraya bakıp sırıtır; dev porsiyon ister.', en: 'Grins into the camera nonstop; wants giant portions.' },
    qty: [8, 12], fx: '✦', fxc: '#ffffff',
    look: { tall: 1, coat: '#1a1a1a', coat2: '#2e2e2e', apron: '#3a3a3a', beard: true, phone: true, hair: '#161010', hairStyle: 0, sk: 1, pants: '#1a1a1a' },
    hi: { tr: 'Heeey! (kameraya sırıtır) … hepsini alıyorum!', en: 'Heeey! (grins at camera) … I\'ll take ALL of it!' },
    bye: { tr: 'Haaa! Çok lezzetli olacak! (sırıtma devam)', en: 'Haaa! Gonna be delicious! (still grinning)' } },
  { id: 'nurettin', n: 'Tuz Baba', fav: 'ton', job: { tr: 'Şov kasabı', en: 'Showman butcher' },
    trait: { tr: 'Tuzu dirsekten döker; bahşişi de şov gibi.', en: 'Sprinkles salt off his elbow; tips like a show.' },
    fx: '·', fxc: '#ffffff', tip: 1.7,
    look: { coat: '#141414', coat2: '#262626', shades: true, hair: '#161010', hairStyle: 8, sk: 1, pants: '#141414' },
    hi: { tr: 'Tuzu dirsekten dökeriz, balığı gözden seçeriz.', en: 'Salt from the elbow, fish chosen by eye.' },
    bye: { tr: '(Dirsekten tuz serper) Ooo, çok şık!', en: '(Sprinkles salt off his elbow) Ooh, very chic!' } },
  { id: 'temel', n: 'Temel', fav: 'hamsi', job: { tr: 'Karadenizli fıkra kahramanı', en: 'Black Sea joke hero' },
    trait: { tr: 'Hamsisiz yapamaz; hep Dursun\'a da götürür.', en: 'Can\'t live without anchovies; always brings some to Dursun.' },
    qty: [6, 9],
    look: { coat: '#1f4e6b', coat2: '#2f6b8f', knit: '#cfe3f0', beanie: '#1a1a1a', thickMust: true, hair: '#161010', hairStyle: 0, sk: 0, pants: '#2b3a45' },
    hi: { tr: 'Uşağum, hamsi yoksa hayat da yoktur!', en: 'Lad, no anchovies, no life!' },
    bye: { tr: 'Dursun\'a da bir kasa, hadi eyvallah!', en: 'One crate for Dursun too — cheers!' } },

  /* ---------- YABANCI ÜNLÜ PARODİLERİ (isimler değiştirildi) ---------- */
  { id: 'gordon', n: 'Gordon Ramsi', fav: 'levrek', job: { tr: 'Öfkeli şef', en: 'Furious chef' },
    trait: { tr: 'Her şeye "ÇİĞ!" diye bağırır; beğenirse çok iyi öder.', en: 'Yells "RAW!" at everything; pays very well if impressed.' },
    fx: '!', fxc: '#ff6b5a', pat: 90, tip: 1.8,
    look: { coat: '#f4f4f0', coat2: '#ffffff', apron: '#2a2a2a', hair: '#e2c47a', hairStyle: 7, sk: 0, pants: '#2a2a2a' },
    hi: { tr: 'BU BALIK ÇİĞ! …ah, fileto mu? Pardon. Harika.', en: 'IT\'S RAW! …oh, it\'s a fillet? Sorry. Lovely.' },
    bye: { tr: 'Aferin. Bu mutfakta ağlayan yok bugün.', en: 'Well done. Nobody cries in this kitchen today.' } },
  { id: 'elvin', n: 'Elvin Presli', fav: 'somon', job: { tr: 'Rock\'n\'roll kralı', en: 'King of rock\'n\'roll' },
    trait: { tr: 'Kalçasını sallayarak gelir; hep "çok teşekkürler" der.', en: 'Arrives shaking his hips; always says "thank you very much".' },
    fx: '♪', fxc: '#ffd76a', dance: true,
    look: { coat: '#f4f0e6', coat2: '#ffffff', cape: '#d9a441', chain: true, shades: true, hair: '#161010', hairStyle: 8, sk: 0, pants: '#f4f0e6' },
    hi: { tr: 'Iıh-hıh… bir kova somon, bebeğim.', en: 'Uh-huh… a bucket of salmon, baby.' },
    bye: { tr: 'Teşekkürler… çok teşekkürler.', en: 'Thank you… thank you very much.' } },
  { id: 'ferdi', n: 'Ferdi Merkür', fav: 'palamut', job: { tr: 'Rock operası solisti', en: 'Rock opera frontman' },
    trait: { tr: 'Kuyrukta "Eeey-oo!" diye bütün limanı coşturur.', en: 'Gets the whole harbour chanting "Ay-oh!" from the queue.' },
    fx: '♪', fxc: '#ffe27a', dance: true, pat: 190,
    look: { coat: '#e8c030', coat2: '#f5d850', thickMust: true, hair: '#161010', hairStyle: 0, sk: 1, pants: '#f4f0e6' },
    hi: { tr: 'Eeey-ooo! Bir palamut, lütfen!', en: 'Ay-ohhh! One bonito, please!' },
    bye: { tr: 'Biz şampiyonuz, dostum!', en: 'We are the champions, my friend!' } },
  { id: 'fasulye', n: 'Bay Fasulye', fav: 'hamsi', job: { tr: 'Sessiz tuhaf adam', en: 'Silent odd fellow' },
    trait: { tr: 'Neredeyse hiç konuşmaz; "Hmm!" der ve garip yüzler yapar.', en: 'Barely speaks; goes "Hmm!" and pulls odd faces.' },
    fx: '?', fxc: '#ffd76a',
    look: { coat: '#6a4a32', coat2: '#83603f', tie: '#b3242a', hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#5a3f2a' },
    hi: { tr: 'Hmm? …Hmm!', en: 'Hmm? …Hmm!' },
    bye: { tr: '(Oyuncak ayısına balığı gösterir) Hıh!', en: '(Shows the fish to his teddy bear) Heh!' } },
  { id: 'serlok', n: 'Şerlok Holmez', fav: 'uskumru', job: { tr: 'Dedektif', en: 'Detective' },
    trait: { tr: 'Balığa bakıp nerede, ne zaman tutulduğunu söyler.', en: 'Deduces where and when a fish was caught at a glance.' },
    fx: '?', fxc: '#c9a15e',
    look: { tall: 1, coat: '#7a6a4a', coat2: '#94835e', cap: '#8a7a55', pipe: true, hair: '#2e2018', hairStyle: 0, sk: 0, pants: '#3a3226' },
    hi: { tr: 'Basit, sevgili tezgâhtar: bu balık bu sabah 6.14\'te tutulmuş.', en: 'Elementary, dear vendor: caught this morning at 6:14.' },
    bye: { tr: 'Dava kapandı. Balık da paketlendi.', en: 'Case closed. Fish wrapped.' } },
  { id: 'sinap', n: 'Şınap Dok', fav: 'somon', job: { tr: 'Rahat rapçi', en: 'Laid-back rapper' },
    trait: { tr: 'Çok yavaş ve rahat konuşur; hiç acelesi yoktur.', en: 'Talks slow and chill; never in a hurry.' },
    fx: '♪', fxc: '#8ef2a2', pat: 280,
    look: { tall: 1, coat: '#2a5a8a', coat2: '#3f78b0', shades: true, chain: true, hair: '#161010', hairStyle: 3, sk: 3, pants: '#1f2a36' },
    hi: { tr: 'Yooo… taze mi bu balık? Fo-şizıl…', en: 'Yooo… is this fish fresh? Fo shizzle…' },
    bye: { tr: 'Keyfine bak, balıkçı dostum.', en: 'Stay chill, fish homie.' } },
  { id: 'kaya', n: 'Kaya Conson', fav: 'ton', job: { tr: 'Güreşçi-oyuncu', en: 'Wrestler-actor' },
    trait: { tr: 'Tek kaşını kaldırır; kasayı tek eliyle taşır, çok alır.', en: 'Raises one eyebrow; carries a crate in one hand, buys a lot.' },
    qty: [8, 12],
    look: { tall: 1, coat: '#1a1a1a', coat2: '#2e2e2e', hair: '#161010', hairStyle: 4, sk: 2, pants: '#2a2a33' },
    hi: { tr: 'Kokuyu alıyor musun… balığın ne pişirdiğini?', en: 'Can you smell… what the fish is cooking?' },
    bye: { tr: 'İşte bu! Kaşım da onaylıyor.', en: 'That\'s it! The eyebrow approves.' } },
  { id: 'arnavut', n: 'Arnavut Şvarzenkol', fav: 'hamsi', job: { tr: 'Emekli terminatör', en: 'Retired terminator' },
    trait: { tr: 'Robot gibi konuşur; her gün mutlaka geri döner.', en: 'Talks like a robot; always comes back.' },
    look: { tall: 1, coat: '#1a1a1a', coat2: '#303030', shades: true, hair: '#3a2a1a', hairStyle: 0, sk: 1, pants: '#1f1f24' },
    hi: { tr: 'Bir kasa hamsi. Hemen.', en: 'One crate of anchovies. Now.' },
    bye: { tr: 'Geri döneceğim… yarın, hamsi için.', en: 'I\'ll be back… tomorrow, for anchovies.' } },
  { id: 'teylan', n: 'Teylan Sivri', fav: 'levrek', job: { tr: 'Pop prensesi', en: 'Pop princess' },
    trait: { tr: 'Her alışveriş hakkında şarkı yazar; hayranları peşinde.', en: 'Writes a song about every purchase; fans follow her everywhere.' },
    fx: '♥', fxc: '#ff8fb0',
    look: { coat: '#e8e2ee', coat2: '#f6f2fa', hair: '#f0d890', hairStyle: 2, sk: 0, skirt: '#b3243a' },
    hi: { tr: 'Bu levrek hakkında da bir şarkı yazacağım.', en: 'I\'m writing a song about this sea bass.' },
    bye: { tr: 'Ve biz… asla… hamsisiz kalmayacağız!', en: 'We are never, ever running out of fish!' } },
  { id: 'opra', n: 'Opra Hanım', fav: 'somon', job: { tr: 'Talk show kraliçesi', en: 'Talk show queen' },
    trait: { tr: 'Kuyruktaki herkese balık ısmarlar!', en: 'Buys fish for everyone in the queue!' },
    qty: [10, 14], tip: 1.3, fx: '$', fxc: '#ffd76a',
    look: { belly: 1, coat: '#6a2a8a', coat2: '#8440a8', hair: '#161010', hairStyle: 5, sk: 3, skirt: '#3a1a4a' },
    hi: { tr: 'Sana balık! Sana balık! Herkese balık!', en: 'You get a fish! You get a fish! Everybody gets a fish!' },
    bye: { tr: 'Hepinize bir kasa, benden olsun!', en: 'A crate for all of you — on me!' } },
  { id: 'mikail', n: 'Mikail Ceksın', fav: 'palamut', job: { tr: 'Pop kralı', en: 'King of pop' },
    trait: { tr: 'Kuyruğa geri geri kayarak gelir (moonwalk).', en: 'Glides into the queue backwards (moonwalk).' },
    fx: '✦', fxc: '#ffffff', moon: true,
    look: { coat: '#b3242a', coat2: '#d03a40', tophat: '#141414', hair: '#161010', hairStyle: 2, sk: 1, pants: '#141414' },
    hi: { tr: 'Hi-hii! Kimse bu palamudu durduramaz!', en: 'Hee-hee! Nobody can stop this bonito!' },
    bye: { tr: 'Şamoon! (geri geri kayarak gider)', en: 'Shamone! (moonwalks away)' } },
  { id: 'bobros', n: 'Bob Rost', fav: 'uskumru', job: { tr: 'Televizyon ressamı', en: 'TV painter' },
    trait: { tr: 'Sakin mi sakin; her şeyde "mutlu küçük kaza" görür.', en: 'Serenely calm; sees a "happy little accident" in everything.' },
    fx: '✦', fxc: '#8fd8ff', pat: 280,
    look: { coat: '#8fb0d0', coat2: '#a8c6e0', beard: true, hair: '#5a3a22', hairStyle: 5, sk: 0, pants: '#2e3a4a' },
    hi: { tr: 'Şuraya mutlu, küçük bir uskumru koyalım…', en: 'Let\'s put a happy little mackerel right here…' },
    bye: { tr: 'Hata yoktur, mutlu küçük kazalar vardır.', en: 'No mistakes, just happy little accidents.' } },
  { id: 'jami', n: 'Jami Olivar', fav: 'levrek', job: { tr: 'Genç şef', en: 'Cheeky chef' },
    trait: { tr: 'Her şeye bir tutam zeytinyağı; "Pukka!" demeden gitmez.', en: 'A drizzle of olive oil on everything; never leaves without "Pukka!".' },
    fx: '·', fxc: '#c8e07a',
    look: { coat: '#5a8ac0', coat2: '#78a4d6', apron: '#e8eef4', hair: '#b08040', hairStyle: 8, sk: 0, pants: '#2a3a4a' },
    hi: { tr: 'Bir tutam zeytinyağı, bir sıkım limon… şahane!', en: 'A drizzle of oil, a squeeze of lemon… gorgeous!' },
    bye: { tr: 'Pukka! Süper, süper!', en: 'Pukka! Lovely jubbly!' } },
  { id: 'atinbara', n: 'Deyvid Atınbara', fav: 'uskumru', job: { tr: 'Belgesel anlatıcısı', en: 'Nature narrator' },
    trait: { tr: 'Fısıldayarak konuşur; kuyruğu vahşi yaşam belgeseli gibi anlatır.', en: 'Whispers; narrates the queue like a wildlife documentary.' },
    pat: 240,
    look: { coat: '#c9b48a', coat2: '#dcc9a0', hair: '#f0f0ea', hairStyle: 1, sk: 0, pants: '#5a4a32' },
    hi: { tr: 'Ve işte… vahşi uskumru, doğal ortamında…', en: 'And here… the wild mackerel, in its natural habitat…' },
    bye: { tr: 'Doğa… ne muhteşem… bir torba daha.', en: 'Nature… how magnificent… one more bag.' } },
  { id: 'cak', n: 'Çak Norıs', fav: 'ton', job: { tr: 'Efsane dövüşçü', en: 'Legendary fighter' },
    trait: { tr: 'Balık tutmaz, balıklar ona teslim olur. Beklemeyi sevmez, parayı fazlasıyla öder.', en: 'Doesn\'t catch fish — fish surrender. Hates waiting, overpays.' },
    fx: '!', fxc: '#ffb27a', pat: 75, tip: 2.0,
    look: { coat: '#3a5a8a', coat2: '#5078aa', sunHat: '#7a5a3a', beard: true, vest: '#2a3f60', hair: '#a0522d', hairStyle: 0, sk: 0, pants: '#2e3a52' },
    hi: { tr: 'Ben sıraya girmem. Sıra bana girer.', en: 'I don\'t wait in line. The line waits for me.' },
    bye: { tr: 'Bu tezgâh artık güvende.', en: 'This stall is now safe.' } },
  { id: 'gigi', n: 'Leydi Gıgı', fav: 'uskumru', job: { tr: 'Avangart pop yıldızı', en: 'Avant-garde pop star' },
    trait: { tr: 'Balıktan elbise giyer. Evet, gerçekten.', en: 'Wears a dress made of fish. Yes, really.' },
    fx: '✦', fxc: '#dfe6ff', tip: 1.4,
    look: { coat: '#8fa9bd', coat2: '#b0c6d6', scales: '#5f7f96', shades: true, hair: '#f4f0e6', hairStyle: 6, sk: 0, skirt: '#6f8fa8' },
    hi: { tr: 'Bu elbiseye bir uskumru daha lazım, darling!', en: 'This dress needs one more mackerel, darling!' },
    bye: { tr: 'Ra-ra-a-a! Moda harikası!', en: 'Rah-rah-ah-ah! Fashion miracle!' } },
  { id: 'edsirin', n: 'Ed Şırın', fav: 'palamut', job: { tr: 'Kızıl şarkıcı', en: 'Ginger songwriter' },
    trait: { tr: 'Gitarıyla gelir, her tezgâha bir aşk şarkısı söyler.', en: 'Shows up with his guitar and sings each stall a love song.' },
    fx: '♪', fxc: '#ffb27a',
    look: { coat: '#7a8088', coat2: '#949aa2', beard: true, guitar: '#b06a2a', hair: '#c2552a', hairStyle: 0, sk: 0, pants: '#2a3a4a' },
    hi: { tr: 'Şeklin hoşuma gidiyor… palamudun yani.', en: 'I\'m in love with the shape of… your bonito.' },
    bye: { tr: 'Mükemmel… tıpkı bu palamut gibi.', en: 'Perfect… just like this bonito.' } },

  /* ---------- KOMİK MESLEKLER ---------- */
  { id: 'mahmut', n: 'Mahmut', fav: 'hamsi', job: { tr: 'Martı terbiyecisi', en: 'Seagull trainer' },
    trait: { tr: 'Omzunda martısıyla gezer; aldığının yarısı martıya.', en: 'Walks around with a gull on his shoulder; half of it goes to the bird.' },
    qty: [5, 8], fx: '~', fxc: '#ffffff',
    look: { coat: '#3a6a8a', coat2: '#5084a6', bird: '#f4f4f0', cap: '#23384a', must: true, hair: '#2e2018', hairStyle: 0, sk: 1, pants: '#2b3a45' },
    hi: { tr: 'Kaptan Martı bugün aç, en tazesinden!', en: 'Captain Gull is hungry today — the freshest!' },
    bye: { tr: 'Martı onayladı: "Gak!"', en: 'The gull approves: "Squawk!"' } },
  { id: 'sabri', n: 'Sabri', fav: 'uskumru', job: { tr: 'Profesyonel sıra bekleyici', en: 'Professional queue-sitter' },
    trait: { tr: 'Başkaları yerine sırada bekler; sabrı sonsuz.', en: 'Waits in line for other people; infinite patience.' },
    pat: 420,
    look: { short: 1, belly: 1, coat: '#8a7a5a', coat2: '#a4946f', sunHat: '#e8dcb8', bag: true, hair: '#6f604b', hairStyle: 4, sk: 1, pants: '#4a4232' },
    hi: { tr: 'Acele yok. Ben işimi yapıyorum: beklemek.', en: 'No rush. I\'m doing my job: waiting.' },
    bye: { tr: 'Bugün 14 sırada bekledim, rekor!', en: 'Fourteen queues today — a record!' } },
  { id: 'bedia', n: 'Bedia Abla', fav: 'levrek', job: { tr: 'Balık pulu falcısı', en: 'Fish-scale fortune teller' },
    trait: { tr: 'Fala balık pulunda bakar; tezgâhına bereket okur.', en: 'Reads fortunes in fish scales; blesses your stall.' },
    fx: '✦', fxc: '#d0a0ff', rep: 6,
    look: { belly: 1, coat: '#5a2a6a', coat2: '#743e88', scarf: '#8a3aa8', scarfDots: '#ffd76a', chain: true, bigBag: '#3a1a4a', hair: '#161010', sk: 1, skirt: '#2a1a3a' },
    hi: { tr: 'Pulunda bir yol görüyorum… ve bir kasa levrek.', en: 'I see a journey in your scales… and a crate of sea bass.' },
    bye: { tr: 'Yolun açık, tezgâhın bereketli olsun!', en: 'Clear roads and full crates to you!' } },
  { id: 'recep', n: 'Tek Göz Recep', fav: 'somon', job: { tr: 'Emekli korsan', en: 'Retired pirate' },
    trait: { tr: 'Göz bandı, omzunda papağan; ödemeyi altınla yapar.', en: 'Eyepatch, parrot on shoulder; pays in gold.' },
    fx: '$', fxc: '#ffd76a', tip: 1.6,
    look: { belly: 1, coat: '#8d2a2a', coat2: '#a8403a', tophat: '#1a1a1a', eyepatch: true, beard: true, bird: '#3aa84a', sash: '#d9a441', hair: '#161010', hairStyle: 2, sk: 1, pants: '#2a2018' },
    hi: { tr: 'Yo-ho-ho! Bir sandık somon, tayfa!', en: 'Yo-ho-ho! A chest of salmon, crew!' },
    bye: { tr: 'Hazine bu tezgâhta saklıymış, arrr!', en: 'So the treasure was in this stall, arrr!' } },
  { id: 'miril', n: 'Mırıl Bey', fav: 'hamsi', job: { tr: 'Kedi sendikası başkanı', en: 'Cat union president' },
    trait: { tr: 'Limanın kedileri adına toplu alım yapar. Pazarlık yok.', en: 'Buys in bulk on behalf of the harbour cats. No haggling.' },
    qty: [9, 12], fx: '♥', fxc: '#ffd0a0',
    look: { coat: '#d08a3a', coat2: '#e8a452', vest: '#3a2f28', bowtie: '#1d1d24', glasses: true, notebook: true, hair: '#9a6a3a', hairStyle: 1, sk: 0, pants: '#3a2f28' },
    hi: { tr: 'Sendikamız adına: 40 kedi, 40 hamsi. Pazarlık yok!', en: 'On behalf of the union: 40 cats, 40 anchovies. No haggling!' },
    bye: { tr: 'Miyav. Yani… teşekkürler.', en: 'Meow. I mean… thank you.' } },
  { id: 'selin', n: 'Selfi Selin', fav: 'somon', job: { tr: 'Fenomen', en: 'Influencer' },
    trait: { tr: 'Almadan önce otuz selfie çeker; ışığı beğenmezse bekler.', en: 'Takes thirty selfies first; waits if the light is wrong.' },
    fx: '✦', fxc: '#ffffff', pat: 180, rep: 5,
    look: { coat: '#f08ab0', coat2: '#ffa8c8', shades: true, phone: true, hair: '#e07aa8', hairStyle: 3, sk: 0, skirt: '#3a2a4a' },
    hi: { tr: 'Dur dur, önce bir selfie! Işık süper!', en: 'Wait wait, selfie first! The light is amazing!' },
    bye: { tr: 'Hikâyeye attım, sen de fenomen oldun!', en: 'Posted it — you\'re famous now!' } }
];
